package com.vahitkeskin.fencecalculator.util

import java.util.Locale
import com.vahitkeskin.fencecalculator.util.localization.*

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    TR("tr", "Türkçe", "🇹🇷"),
    EN("en", "English", "🇺🇸"),
    DE("de", "Deutsch", "🇩🇪"),
    FR("fr", "Français", "🇫🇷"),
    ES("es", "Español", "🇪🇸"),
    IT("it", "Italiano", "🇮🇹"),
    PT("pt", "Português", "🇵🇹"),
    NL("nl", "Nederlands", "🇳🇱"),
    RU("ru", "Русский", "🇷🇺"),
    AR("ar", "العربية", "🇸🇦"),
    ZH("zh", "中文", "🇨🇳");

    companion object {
        fun fromCode(code: String): AppLanguage {
            return entries.find { it.code == code } ?: EN
        }

        fun detectSystemLanguage(): AppLanguage {
            val systemLocale = Locale.getDefault().language
            return entries.find { it.code == systemLocale } ?: EN
        }
    }
}

data class AppStrings(
    val appName: String,
    val readyCalculations: String,
    val settings: String,
    val about: String,
    val personalInfo: String,
    val companyName: String,
    val iban: String,
    val invalidIban: String,
    val pin: String,
    val share: String,
    val shareAppTitle: String,
    val shareAppMessage: String,
    val useCamera: String,
    val selectFromGallery: String,
    val fenceCalculation: String,
    val premiumArchitecturalTool: String,
    val customerNameSurname: String,
    val preparingPdfReport: String,
    val customCards: String,
    val createNewCard: String,
    val calculationParameters: String,
    val calculationParametersDesc: String,
    val loadDefaultCards: String,
    val cardTitleRequired: String,
    val descriptionNote: String,
    val quantityValue: String,
    val quantity: String,
    val unitPriceTl: String,
    val pdfLoadFailed: String,
    val whatsapp: String,
    val currencySymbol: String,
    val currencyFormat: String,
    val defaultValueLabel: String,
    val unitLabel: String,
    val unitPiece: String,
    val unitMeter: String,
    val unitKg: String,
    val unitLiter: String,
    val unitUnit: String,
    val unitTl: String,
    val unitRoll: String,
    val unitM3: String,
    val searchCountryOrCode: String,
    val totalLabel: String,
    val calculatedAmount: String,
    val totalCostLabel: String,
    val customerInfo: String,
    val favoriteCalculations: String,
    val sharePdf: String,
    val infoTextHome: String,
    val navHome: String,
    val navCalculations: String,
    val navCustom: String,
    val navProfile: String,
    val back: String,
    val companyInfoTitle: String,
    val paymentInfoTitle: String,
    val scanQrCode: String,
    val scanQrCodeTitle: String,
    val cameraPermissionRequired: String,
    val ibanQrCodeDesc: String,
    val qrCodeSharingDesc: String,
    val noCardsYet: String,
    val noCardsDesc: String,
    val editCard: String,
    val addNewCard: String,
    val manualEntry: String,
    val quantityAndUnit: String,
    val selectReferenceCard: String,
    val selectOperation: String,
    val opAdd: String,
    val opSub: String,
    val opMul: String,
    val opDiv: String,
    val calcPreviewResult: String,
    val previewTitle: String,
    val totalPreviewText: String,
    val update: String,
    val save: String,
    val deleteCard: String,
    val appearanceSettings: String,
    val themeLight: String,
    val themeDark: String,
    val themeSystem: String,
    val languageSettings: String,
    val fencePostDimensions: String,
    val fenceHeightM: String,
    val poleSpacingM: String,
    val wireThicknessMm: String,
    val meshEyeCm: String,
    val weightConstant: String,
    val strutSetup: String,
    val strutIntervalPosts: String,
    val strutCountPer: String,
    val meshRollSpecs: String,
    val meshRollLengthM: String,
    val barbedWireRows: String,
    val barbedWireRollM: String,
    val advancedParameters: String,
    val poleLengthM: String,
    val pipeLengthM: String,
    val tensionFactor: String,
    val bindingFactor: String,
    val cementFactor: String,
    val concreteFactor: String,
    val aboutAppTitle: String,
    val appDescriptionLong: String,
    val developerLabel: String,
    val feedback: String,
    val feedbackDesc: String,
    val licenses: String,
    val licensesDesc: String,
    val allRightsReserved: String,
    val pdfDefaultTitle: String,
    val pdfTotalLengthLabel: String,
    val pdfHeaderMaterial: String,
    val pdfHeaderQty: String,
    val pdfHeaderUnitPrice: String,
    val pdfHeaderTotal: String,
    val pdfGrandTotal: String,
    val pdfSharingSubject: String,
    val pdfIbanCopiedToast: String,
    val pdfShareFileSubject: String,
    val pdfShareFileText: String,
    val pdfShareChooserTitle: String,
    val pdfPreviewTitle: String,
    val close: String,
    val shareAsPdf: String,
    val customerPhoneNo: String,
    val selectCountry: String,
    val unitPriceLabel: String,
    val direkTitle: String,
    val direkDesc: String,
    val boyDemirTitle: String,
    val boyDemirDesc: String,
    val payandaTitle: String,
    val payandaDesc: String,
    val kafesTopTitle: String,
    val kafesTopDesc: String,
    val kafesKgTitle: String,
    val kafesKgDesc: String,
    val dikenTitle: String,
    val dikenDesc: String,
    val gergiTitle: String,
    val gergiDesc: String,
    val baglamaTitle: String,
    val baglamaDesc: String,
    val cimentoTitle: String,
    val cimentoDesc: String,
    val betonTitle: String,
    val betonDesc: String,
    val catMetal: String,
    val catWire: String,
    val catConstruction: String,
    val catGeneral: String,
    val onboardingWelcomeTitle: String,
    val onboardingWelcomeDesc: String,
    val onboardingStep1Title: String,
    val onboardingStep1Desc: String,
    val onboardingStep2Title: String,
    val onboardingStep2Desc: String,
    val onboardingStep3Title: String,
    val onboardingStep3Desc: String,
    val onboardingFinish: String,
    val next: String,
    val skip: String,
    val lockTooltip: String,
    val landLengthUsageInfo: String,
    val premiumRequiredForMore: String,
    val usageLimitReached: String,
    val apply: String,
    val calculate: String,
    val premiumPopupTitle: String,
    val premiumPopupDesc: String,
    val premiumPopupConfirm: String,
    val privateDnsDetectedTitle: String,
    val privateDnsDetectedMessage: String,
    val goToDnsSettings: String,
    val adLoading: String,
    val shareReportTitle: String,
    val shareLandLength: String,
    val shareMaterialList: String,
    val shareAmountLabel: String,
    val shareGrandTotal: String,
    val shareCalculatedWith: String,
    val shareReportSubject: String,
    val shareReportChooser: String,
    val cardEmoji: String,
    val emojiCategoryConstruction: String,
    val emojiCategoryNature: String,
    val cardColor: String,
    val selected: String,
    val emojiCategoryNails: String,
    val splashTitle: String
)


object Localization {
    private val languages = mapOf(
        "tr" to TrStrings,
        "en" to EnStrings,
        "de" to DeStrings,
        "fr" to FrStrings,
        "es" to EsStrings,
        "it" to ItStrings,
        "pt" to PtStrings,
        "nl" to NlStrings,
        "ru" to RuStrings,
        "ar" to ArStrings,
        "zh" to ZhStrings
    )

    private val en = EnStrings

    fun getStrings(locale: String): AppStrings {
        return languages[locale] ?: en
    }

}
