package com.vahitkeskin.fencecalculator.util

import java.util.Locale

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    TR("tr", "Türkçe", "🇹🇷"),
    EN("en", "English", "🇺🇸"),
    DE("de", "Deutsch", "🇩🇪"),
    FR("fr", "Français", "🇫🇷"),
    ES("es", "Español", "🇪🇸"),
    IT("it", "Italiano", "🇮🇹"),
    PT("pt", "Português", "🇵🇹"),
    NL("nl", "Nederlands", "🇳🇱"),
    RU("ru", "Русский", "🇷🇺"),
    AR("ar", "العربية", "🇸🇦"),
    ZH("zh", "中文", "🇨🇳");

    companion object {
        fun fromCode(code: String): AppLanguage {
            return entries.find { it.code == code } ?: EN
        }

        fun detectSystemLanguage(): AppLanguage {
            val systemLocale = Locale.getDefault().language
            return entries.find { it.code == systemLocale } ?: EN
        }
    }
}

data class AppStrings(
    val appName: String,
    val readyCalculations: String,
    val settings: String,
    val about: String,
    val personalInfo: String,
    val companyName: String,
    val iban: String,
    val invalidIban: String,
    val pin: String,
    val share: String,
    val shareAppTitle: String,
    val shareAppMessage: String,
    val useCamera: String,
    val selectFromGallery: String,
    val fenceCalculation: String,
    val premiumArchitecturalTool: String,
    val customerNameSurname: String,
    val preparingPdfReport: String,
    val customCards: String,
    val createNewCard: String,
    val calculationParameters: String,
    val calculationParametersDesc: String,
    val loadDefaultCards: String,
    val cardTitleRequired: String,
    val descriptionNote: String,
    val quantityValue: String,
    val quantity: String,
    val unitPriceTl: String,
    val pdfLoadFailed: String,
    val whatsapp: String,
    val currencySymbol: String,
    val currencyFormat: String,
    val defaultValueLabel: String,
    val unitLabel: String,
    val unitPiece: String,
    val unitMeter: String,
    val unitKg: String,
    val unitLiter: String,
    val unitUnit: String,
    val unitTl: String,
    val unitRoll: String,
    val unitM3: String,
    val searchCountryOrCode: String,
    val totalLabel: String,
    val calculatedAmount: String,
    val totalCostLabel: String,
    val customerInfo: String,
    val favoriteCalculations: String,
    val sharePdf: String,
    val infoTextHome: String,
    val navHome: String,
    val navCalculations: String,
    val navCustom: String,
    val navProfile: String,
    val back: String,
    val companyInfoTitle: String,
    val paymentInfoTitle: String,
    val scanQrCode: String,
    val scanQrCodeTitle: String,
    val cameraPermissionRequired: String,
    val ibanQrCodeDesc: String,
    val qrCodeSharingDesc: String,
    val noCardsYet: String,
    val noCardsDesc: String,
    val editCard: String,
    val addNewCard: String,
    val manualEntry: String,
    val quantityAndUnit: String,
    val selectReferenceCard: String,
    val selectOperation: String,
    val opAdd: String,
    val opSub: String,
    val opMul: String,
    val opDiv: String,
    val calcPreviewResult: String,
    val previewTitle: String,
    val totalPreviewText: String,
    val update: String,
    val save: String,
    val deleteCard: String,
    val appearanceSettings: String,
    val themeLight: String,
    val themeDark: String,
    val themeSystem: String,
    val languageSettings: String,
    val fencePostDimensions: String,
    val fenceHeightM: String,
    val poleSpacingM: String,
    val wireThicknessMm: String,
    val meshEyeCm: String,
    val weightConstant: String,
    val strutSetup: String,
    val strutIntervalPosts: String,
    val strutCountPer: String,
    val meshRollSpecs: String,
    val meshRollLengthM: String,
    val barbedWireRows: String,
    val barbedWireRollM: String,
    val advancedParameters: String,
    val poleLengthM: String,
    val pipeLengthM: String,
    val tensionFactor: String,
    val bindingFactor: String,
    val cementFactor: String,
    val concreteFactor: String,
    val aboutAppTitle: String,
    val appDescriptionLong: String,
    val developerLabel: String,
    val feedback: String,
    val feedbackDesc: String,
    val licenses: String,
    val licensesDesc: String,
    val allRightsReserved: String,
    val pdfDefaultTitle: String,
    val pdfTotalLengthLabel: String,
    val pdfHeaderMaterial: String,
    val pdfHeaderQty: String,
    val pdfHeaderUnitPrice: String,
    val pdfHeaderTotal: String,
    val pdfGrandTotal: String,
    val pdfSharingSubject: String,
    val pdfIbanCopiedToast: String,
    val pdfShareFileSubject: String,
    val pdfShareFileText: String,
    val pdfShareChooserTitle: String,
    val pdfPreviewTitle: String,
    val close: String,
    val shareAsPdf: String,
    val customerPhoneNo: String,
    val selectCountry: String,
    val unitPriceLabel: String,
    val direkTitle: String,
    val direkDesc: String,
    val boyDemirTitle: String,
    val boyDemirDesc: String,
    val payandaTitle: String,
    val payandaDesc: String,
    val kafesTopTitle: String,
    val kafesTopDesc: String,
    val kafesKgTitle: String,
    val kafesKgDesc: String,
    val dikenTitle: String,
    val dikenDesc: String,
    val gergiTitle: String,
    val gergiDesc: String,
    val baglamaTitle: String,
    val baglamaDesc: String,
    val cimentoTitle: String,
    val cimentoDesc: String,
    val betonTitle: String,
    val betonDesc: String,
    val catMetal: String,
    val catWire: String,
    val catConstruction: String,
    val catGeneral: String
)


object Localization {
    private val tr = AppStrings(
        appName = "Tel Çit Hesaplama",
        readyCalculations = "HAZIR HESAPLAR",
        settings = "AYARLAR",
        about = "Hakkında",
        personalInfo = "KİŞİSEL BİLGİLER",
        companyName = "Firma Adı",
        iban = "IBAN",
        invalidIban = "Geçersiz IBAN formatı",
        pin = "İğnele",
        share = "Paylaş",
        shareAppTitle = "Paylaş",
        shareAppMessage = "Çit ve örgü tel ihtiyaçlarınıza profesyonel çözüm!\n%s uygulamasını hemen indirin:\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "Kamerayı Kullan",
        selectFromGallery = "Galeriden Seç",
        fenceCalculation = "ÇİT HESAPLAMA",
        premiumArchitecturalTool = "PREMIUM MIMARI ARAÇ",
        customerNameSurname = "Müşteri Adı Soyadı",
        preparingPdfReport = "PDF Raporu Hazırlanıyor...",
        customCards = "ÖZEL KARTLAR",
        createNewCard = "YENİ KART OLUŞTUR",
        calculationParameters = "Hesaplama Parametreleri",
        calculationParametersDesc = "Değerleri değiştirdiğinizde anlık olarak hesaplanır.",
        loadDefaultCards = "Varsayılan Kartları Yükle",
        cardTitleRequired = "Kart Başlığı *",
        descriptionNote = "Açıklama / Not",
        quantityValue = "Miktar / Değer",
        quantity = "Miktar",
        unitPriceTl = "Birim Fiyat (₺)",
        pdfLoadFailed = "PDF Yüklenemedi",
        whatsapp = "WhatsApp",
        currencySymbol = "₺",
        currencyFormat = "%s ₺",
        defaultValueLabel = "Varsayılan: %s",
        unitLabel = "BİRİM",
        unitPiece = "Adet",
        unitMeter = "Metre",
        unitKg = "Kg",
        unitLiter = "Litre",
        unitUnit = "Birim",
        unitTl = "TL",
        unitRoll = "Top",
        unitM3 = "m³",
        searchCountryOrCode = "Ülke veya kod ara...",
        totalLabel = "TOPLAM",
        calculatedAmount = "Hesaplanan Tutar",
        totalCostLabel = "TOPLAM MALİYET",
        customerInfo = "MÜŞTERİ BİLGİLERİ",
        favoriteCalculations = "FAVORİ HESAPLAMALAR",
        sharePdf = "PDF Paylaş",
        infoTextHome = "Hesaplama detaylarını görmek için alttaki 'Hesaplar' veya 'Özel' sekmelerini kullanın.",
        navHome = "Anasayfa",
        navCalculations = "Hesaplar",
        navCustom = "Özel",
        navProfile = "Profil",
        back = "Geri",
        companyInfoTitle = "FİRMA BİLGİLERİ",
        paymentInfoTitle = "ÖDEME BİLGİLERİ",
        scanQrCode = "Karekod Tara",
        scanQrCodeTitle = "KAREKOD TARA",
        cameraPermissionRequired = "Kamera izni gerekli",
        ibanQrCodeDesc = "IBAN Karekod",
        qrCodeSharingDesc = "Paylaşımda görünecek karekod",
        noCardsYet = "Henüz Kart Yok",
        noCardsDesc = "Kendi özel hesaplama kartlarınızı oluşturarak uygulamayı kişiselleştirin.",
        editCard = "KARTI DÜZENLE",
        addNewCard = "YENİ KART EKLE",
        manualEntry = "MANUEL GİRİŞ",
        quantityAndUnit = "MİKTAR & BİRİM",
        selectReferenceCard = "REFERANS KART SEÇİN",
        selectOperation = "İŞLEM SEÇİN",
        opAdd = "Topla",
        opSub = "Çıkar",
        opMul = "Çarp",
        opDiv = "Böl",
        calcPreviewResult = "Sonuç: %d %s %s %.1f = %d %s",
        previewTitle = "ÖNİZLEME",
        totalPreviewText = "Toplam: %s ₺",
        update = "GÜNCELLE",
        save = "KAYDET",
        deleteCard = "KARTI SİL",
        appearanceSettings = "Görünüm Ayarları",
        themeLight = "Açık",
        themeDark = "Koyu",
        themeSystem = "Sistem",
        languageSettings = "Dil Ayarları",
        fencePostDimensions = "Çit ve Direk Ölçüleri",
        fenceHeightM = "Çit Yüksekliği (m)",
        poleSpacingM = "Direk Aralığı (m)",
        wireThicknessMm = "Tel Kalınlığı (mm)",
        meshEyeCm = "Göz Aralığı (cm)",
        weightConstant = "Sabit Çarpan",
        strutSetup = "Payanda Kurulumu",
        strutIntervalPosts = "Sıklık (Direk)",
        strutCountPer = "Adet (Her Sefer)",
        meshRollSpecs = "Tel Rulo Özellikleri",
        meshRollLengthM = "Kafes Tel Top Uzunluğu (m)",
        barbedWireRows = "Dikenli Tel (Sıra)",
        barbedWireRollM = "Dikenli Top (m)",
        advancedParameters = "Gelişmiş Parametreler",
        poleLengthM = "Direk Boyu (m)",
        pipeLengthM = "Boru Boyu (m)",
        tensionFactor = "Gergi Katsayı",
        bindingFactor = "Bağlama Katsayı",
        cementFactor = "Çimento Katsayı",
        concreteFactor = "Beton Katsayı",
        aboutAppTitle = "Uygulama Hakkında",
        appDescriptionLong = "%s, çit ve örgü tel ihtiyaçlarınız için profesyonel bir hesaplama asistanıdır.",
        developerLabel = "Geliştirici",
        feedback = "Geri Bildirim",
        feedbackDesc = "Hata bildir veya öneri sun",
        licenses = "Lisanslar",
        licensesDesc = "Açık kaynak kütüphaneleri",
        allRightsReserved = "© %d %s. Tüm hakları saklıdır.",
        pdfDefaultTitle = "ÇİT HESAPLAMA",
        pdfTotalLengthLabel = "Toplam Arazi Uzunluğu:",
        pdfHeaderMaterial = "MALZEME",
        pdfHeaderQty = "MİKTAR",
        pdfHeaderUnitPrice = "BİRİM FİYAT",
        pdfHeaderTotal = "TUTAR",
        pdfGrandTotal = "GENEL TOPLAM MALİYET",
        pdfSharingSubject = "Maliyet Teklifi",
        pdfIbanCopiedToast = "IBAN kopyalandı!",
        pdfShareFileSubject = "Çit Maliyet Teklifi",
        pdfShareFileText = "Ekte çit maliyet hesaplama detaylı raporunu bulabilirsiniz.",
        pdfShareChooserTitle = "PDF Raporunu Paylaş",
        pdfPreviewTitle = "Teklif Önizleme",
        close = "Kapat",
        shareAsPdf = "PDF Olarak Paylaş",
        customerPhoneNo = "Müşteri Telefon No",
        selectCountry = "ÜLKE SEÇİN",
        unitPriceLabel = "Birim Fiyat (₺)",
        direkTitle = "Direk",
        direkDesc = "Her %s m'de bir",
        boyDemirTitle = "Boy Demir Boru",
        boyDemirDesc = "%s m (Her borudan %s m'lik direk)",
        payandaTitle = "Payanda",
        payandaDesc = "Her %s direkte %s adet",
        kafesTopTitle = "Kafes Tel (Toplam)",
        kafesTopDesc = "%s m'lik top (%s m Yükseklik)",
        kafesKgTitle = "1 Top Tel Ağırlığı",
        kafesKgDesc = "1 Rulo (%s m) ağırlığıdır.",
        dikenTitle = "Dikenli Tel",
        dikenDesc = "%d Sıra (%s m/top)",
        gergiTitle = "Gergi Teli",
        gergiDesc = "Uzunluk / %s",
        baglamaTitle = "Bağlama Teli",
        baglamaDesc = "Gergi Telinin 1/%s'ü",
        cimentoTitle = "Çimento (50 Kg)",
        cimentoDesc = "Direk Sayısı / %s",
        betonTitle = "Hazır Beton",
        betonDesc = "Direk Sayısı / %s",
        catMetal = "METAL",
        catWire = "TEL",
        catConstruction = "İNŞAAT",
        catGeneral = "GENEL"
    )


    private val it = AppStrings(
        appName = "Calcolatore di Recinzioni",
        readyCalculations = "CALCOLI PRONTI",
        settings = "IMPOSTAZIONI",
        about = "Informazioni",
        personalInfo = "INFO PERSONALI",
        companyName = "Nome Azienda",
        iban = "IBAN",
        invalidIban = "Formato IBAN non valido",
        pin = "Fissa",
        share = "Condividi",
        shareAppTitle = "Condividi",
        shareAppMessage = "Soluzione professionale per le tue esigenze di recinzioni e reti!\nScarica %s ora:\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "Usa fotocamera",
        selectFromGallery = "Seleziona dalla galleria",
        fenceCalculation = "CALCOLO RECINZIONE",
        premiumArchitecturalTool = "STRUMENTO ARCHITETTONICO PREMIUM",
        customerNameSurname = "Nome Cliente",
        preparingPdfReport = "Preparazione rapporto PDF...",
        customCards = "SCHEDE PERSONALIZZATE",
        createNewCard = "CREA NUOVA SCHEDA",
        calculationParameters = "Parametri di calcolo",
        calculationParametersDesc = "Le modifiche vengono calcolate istantaneamente.",
        loadDefaultCards = "Carica schede predefinite",
        cardTitleRequired = "Titolo scheda *",
        descriptionNote = "Descrizione / Nota",
        quantityValue = "Quantità / Valore",
        quantity = "Quantità",
        unitPriceTl = "Prezzo unitario (€)",
        pdfLoadFailed = "Caricamento PDF fallito",
        whatsapp = "WhatsApp",
        currencySymbol = "€",
        currencyFormat = "%s €",
        defaultValueLabel = "Predefinito: %s",
        unitLabel = "UNITÀ",
        unitPiece = "Pezzo",
        unitMeter = "Metro",
        unitKg = "kg",
        unitLiter = "Litro",
        unitUnit = "Unità",
        unitTl = "€",
        unitRoll = "Rotolo",
        unitM3 = "m³",
        searchCountryOrCode = "Cerca paese o codice...",
        totalLabel = "TOTALE",
        calculatedAmount = "Importo calcolato",
        totalCostLabel = "COSTO TOTALE",
        customerInfo = "INFORMAZIONI CLIENTE",
        favoriteCalculations = "PREFERITI",
        sharePdf = "Condividi PDF",
        infoTextHome = "Usa le schede 'Libreria' o 'Personale' qui sotto per vedere i dettagli del calcolo.",
        navHome = "Home",
        navCalculations = "Libreria",
        navCustom = "Personale",
        navProfile = "Profilo",
        back = "Indietro",
        companyInfoTitle = "INFORMAZIONI AZIENDALI",
        paymentInfoTitle = "INFORMAZIONI DI PAGAMENTO",
        scanQrCode = "Scansiona codice QR",
        scanQrCodeTitle = "SCANSIONA CODICE QR",
        cameraPermissionRequired = "Permesso fotocamera richiesto",
        ibanQrCodeDesc = "Codice QR IBAN",
        qrCodeSharingDesc = "Codice QR che apparirà nella condivisione",
        noCardsYet = "Nessuna scheda ancora",
        noCardsDesc = "Personalizza l'app creando le tue schede di calcolo personalizzate.",
        editCard = "MODIFICA SCHEDA",
        addNewCard = "AGGIUNGI NUOVA SCHEDA",
        manualEntry = "INSERIMENTO MANUALE",
        quantityAndUnit = "QUANTITÀ E UNITÀ",
        selectReferenceCard = "SELEZIONA SCHEDA DI RIFERIMENTO",
        selectOperation = "SELEZIONA OPERAZIONE",
        opAdd = "Aggiungi",
        opSub = "Sottrai",
        opMul = "Moltiplica",
        opDiv = "Dividi",
        calcPreviewResult = "Risultato: %d %s %s %.1f = %d %s",
        previewTitle = "ANTEPRIMA",
        totalPreviewText = "Totale: %s €",
        update = "AGGIORNA",
        save = "SALVA",
        deleteCard = "ELIMINA SCHEDA",
        appearanceSettings = "Impostazioni aspetto",
        themeLight = "Chiaro",
        themeDark = "Scuro",
        themeSystem = "Sistema",
        languageSettings = "Impostazioni lingua",
        fencePostDimensions = "Dimensioni recinzione e pali",
        fenceHeightM = "Altezza recinzione (m)",
        poleSpacingM = "Spaziatura pali (m)",
        wireThicknessMm = "Spessore filo (mm)",
        meshEyeCm = "Maglia (cm)",
        weightConstant = "Costante di peso",
        strutSetup = "Installazione saette",
        strutIntervalPosts = "Intervallo (pali)",
        strutCountPer = "Quantità (ogni volta)",
        meshRollSpecs = "Specifiche rotolo rete",
        meshRollLengthM = "Lunghezza rotolo (m)",
        barbedWireRows = "Filo spinato (file)",
        barbedWireRollM = "Rotolo spinato (m)",
        advancedParameters = "Parametri avanzati",
        poleLengthM = "Lunghezza palo (m)",
        pipeLengthM = "Lunghezza tubo (m)",
        tensionFactor = "Fattore di tensione",
        bindingFactor = "Fattore di legatura",
        cementFactor = "Fattore di cemento",
        concreteFactor = "Fattore di calcestruzzo",
        aboutAppTitle = "Informazioni sull'app",
        appDescriptionLong = "%s è un assistente di calcolo professionale per le tue esigenze di recinzioni e reti.",
        developerLabel = "Sviluppatore",
        feedback = "Feedback",
        feedbackDesc = "Segnala un bug o suggerisci una funzione",
        licenses = "Licenze",
        licensesDesc = "Librerie open source",
        allRightsReserved = "© %d %s. Tutti i diritti riservati.",
        pdfDefaultTitle = "CALCOLO RECINZIONE",
        pdfTotalLengthLabel = "Lunghezza totale area:",
        pdfHeaderMaterial = "MATERIALE",
        pdfHeaderQty = "QUANTITÀ",
        pdfHeaderUnitPrice = "PREZZO UNITARIO",
        pdfHeaderTotal = "IMPORTO TOTALE",
        pdfGrandTotal = "COSTO GENERALE TOTALE",
        pdfSharingSubject = "Stima dei costi",
        pdfIbanCopiedToast = "IBAN copiato!",
        pdfShareFileSubject = "Stima del costo della recinzione",
        pdfShareFileText = "In allegato trovi il rapporto dettagliato del calcolo del costo della recinzione.",
        pdfShareChooserTitle = "Condividi rapporto PDF",
        pdfPreviewTitle = "Anteprima stima",
        close = "Chiudi",
        shareAsPdf = "Condividi come PDF",
        customerPhoneNo = "N. telefono cliente",
        selectCountry = "SELEZIONA PAESE",
        unitPriceLabel = "Prezzo unitario (€)",
        direkTitle = "Palo",
        direkDesc = "Ogni %s m",
        boyDemirTitle = "Tubo di ferro",
        boyDemirDesc = "%s m (Ogni tubo produce %s m di palo)",
        payandaTitle = "Saetta",
        payandaDesc = "%s unità ogni %s pali",
        kafesTopTitle = "Rete (Totale)",
        kafesTopDesc = "Rotolo da %s m (%s m di altezza)",
        kafesKgTitle = "Peso di 1 rotolo di filo",
        kafesKgDesc = "Peso per 1 rotolo (%s m).",
        dikenTitle = "Filo spinato",
        dikenDesc = "%d file (%s m/rotolo)",
        gergiTitle = "Filo di tensione",
        gergiDesc = "Lunghezza / %s",
        baglamaTitle = "Filo di legatura",
        baglamaDesc = "1/%s del filo di tensione",
        cimentoTitle = "Cemento (50 kg)",
        cimentoDesc = "Numero pali / %s",
        betonTitle = "Calcestruzzo preconfezionato",
        betonDesc = "Numero pali / %s",
        catMetal = "METALLO",
        catWire = "FILO",
        catConstruction = "COSTRUZIONE",
        catGeneral = "GENERALE"
    )


    private val pt = AppStrings(
        appName = "Calculadora de Cercas",
        readyCalculations = "CÁLCULOS PRONTOS",
        settings = "CONFIGURAÇÕES",
        about = "Sobre",
        personalInfo = "INFORMAÇÕES PESSOAIS",
        companyName = "Nome da Empresa",
        iban = "IBAN",
        invalidIban = "Formato IBAN inválido",
        pin = "Fixar",
        share = "Compartilhar",
        shareAppTitle = "Compartilhar",
        shareAppMessage = "Solução profissional para suas necessidades de cercas e telas!\nBaixe o %s agora:\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "Usar câmera",
        selectFromGallery = "Selecionar da galeria",
        fenceCalculation = "CÁLCULO DE CERCA",
        premiumArchitecturalTool = "FERRAMENTA ARQUITETÔNICA PREMIUM",
        customerNameSurname = "Nome do Cliente",
        preparingPdfReport = "Preparando relatório PDF...",
        customCards = "CARTÕES PERSONALIZADOS",
        createNewCard = "CRIAR NOVO CARTÃO",
        calculationParameters = "Parâmetros de Cálculo",
        calculationParametersDesc = "As alterações são calculadas instantaneamente.",
        loadDefaultCards = "Carregar cartões padrão",
        cardTitleRequired = "Título do cartão *",
        descriptionNote = "Descrição / Nota",
        quantityValue = "Quantidade / Valor",
        quantity = "Quantidade",
        unitPriceTl = "Preço unitario (€)",
        pdfLoadFailed = "Falha ao carregar PDF",
        whatsapp = "WhatsApp",
        currencySymbol = "€",
        currencyFormat = "%s €",
        defaultValueLabel = "Padrão: %s",
        unitLabel = "UNIDADE",
        unitPiece = "Peça",
        unitMeter = "Metro",
        unitKg = "kg",
        unitLiter = "Litro",
        unitUnit = "Unidade",
        unitTl = "€",
        unitRoll = "Rolo",
        unitM3 = "m³",
        searchCountryOrCode = "Buscar país ou código...",
        totalLabel = "TOTAL",
        calculatedAmount = "Valor calculado",
        totalCostLabel = "CUSTO TOTAL",
        customerInfo = "INFORMAÇÕES DO CLIENTE",
        favoriteCalculations = "FAVORITOS",
        sharePdf = "Compartilhar PDF",
        infoTextHome = "Use as abas 'Biblioteca' ou 'Pessoal' abaixo para ver os detalhes do cálculo.",
        navHome = "Início",
        navCalculations = "Biblioteca",
        navCustom = "Pessoal",
        navProfile = "Perfil",
        back = "Voltar",
        companyInfoTitle = "INFORMAÇÕES DA EMPRESA",
        paymentInfoTitle = "INFORMAÇÕES DE PAGAMENTO",
        scanQrCode = "Escanear código QR",
        scanQrCodeTitle = "ESCANEAR CÓDIGO QR",
        cameraPermissionRequired = "Permissão de câmera necessária",
        ibanQrCodeDesc = "Código QR do IBAN",
        qrCodeSharingDesc = "Código QR que aparecerá no compartilhamento",
        noCardsYet = "Nenhum cartão ainda",
        noCardsDesc = "Personalize o aplicativo criando seus próprios cartões de cálculo personalizados.",
        editCard = "EDITAR CARTÃO",
        addNewCard = "ADICIONAR NOVO CARTÃO",
        manualEntry = "ENTRADA MANUAL",
        quantityAndUnit = "QUANTIDADE E UNIDADE",
        selectReferenceCard = "SELECIONAR CARTÃO DE REFERÊNCIA",
        selectOperation = "SELECIONAR OPERAÇÃO",
        opAdd = "Adicionar",
        opSub = "Subtrair",
        opMul = "Multiplicar",
        opDiv = "Dividir",
        calcPreviewResult = "Resultado: %d %s %s %.1f = %d %s",
        previewTitle = "PRÉ-VISUALIZAÇÃO",
        totalPreviewText = "Total: %s €",
        update = "ATUALIZAR",
        save = "SALVAR",
        deleteCard = "EXCLUIR CARTÃO",
        appearanceSettings = "Configurações de aparência",
        themeLight = "Claro",
        themeDark = "Escuro",
        themeSystem = "Sistema",
        languageSettings = "Configurações de idioma",
        fencePostDimensions = "Dimensões da cerca e dos postes",
        fenceHeightM = "Altura da cerca (m)",
        poleSpacingM = "Espaçamento entre postes (m)",
        wireThicknessMm = "Espessura do arame (mm)",
        meshEyeCm = "Malha (cm)",
        weightConstant = "Constante de peso",
        strutSetup = "Instalação de escoras",
        strutIntervalPosts = "Intervalo (postes)",
        strutCountPer = "Quantidade (a cada vez)",
        meshRollSpecs = "Especificações do rolo de tela",
        meshRollLengthM = "Comprimento do rolo (m)",
        barbedWireRows = "Arame farpado (carreiras)",
        barbedWireRollM = "Rolo de farpado (m)",
        advancedParameters = "Parâmetros avançados",
        poleLengthM = "Comprimento do poste (m)",
        pipeLengthM = "Comprimento do tubo (m)",
        tensionFactor = "Factor de tensão",
        bindingFactor = "Factor de amarração",
        cementFactor = "Factor de cimento",
        concreteFactor = "Factor de betão",
        aboutAppTitle = "Sobre o aplicativo",
        appDescriptionLong = "O %s é um assistente de cálculo profissional para suas necessidades de cercas e telas.",
        developerLabel = "Desenvolvedor",
        feedback = "Feedback",
        feedbackDesc = "Relatar um erro ou sugerir um recurso",
        licenses = "Licenças",
        licensesDesc = "Bibliotecas de código aberto",
        allRightsReserved = "© %d %s. Todos os direitos reservados.",
        pdfDefaultTitle = "CÁLCULO DE CERCA",
        pdfTotalLengthLabel = "Comprimento total da área:",
        pdfHeaderMaterial = "MATERIAL",
        pdfHeaderQty = "QUANTIDADE",
        pdfHeaderUnitPrice = "PREÇO UNITÁRIO",
        pdfHeaderTotal = "VALOR TOTAL",
        pdfGrandTotal = "CUSTO TOTAL GERAL",
        pdfSharingSubject = "Estimativa de custos",
        pdfIbanCopiedToast = "IBAN copiado!",
        pdfShareFileSubject = "Estimativa de custo de cerca",
        pdfShareFileText = "Segue em anexo o relatório detalhado do cálculo do custo da cerca.",
        pdfShareChooserTitle = "Compartilhar relatório PDF",
        pdfPreviewTitle = "Visualização da estimativa",
        close = "Fechar",
        shareAsPdf = "Compartilhar como PDF",
        customerPhoneNo = "Nº de telefone do cliente",
        selectCountry = "SELECIONAR PAÍS",
        unitPriceLabel = "Preço unitário (€)",
        direkTitle = "Poste",
        direkDesc = "A cada %s m",
        boyDemirTitle = "Tubo de ferro",
        boyDemirDesc = "%s m (Cada tubo rende um poste de %s m)",
        payandaTitle = "Escora",
        payandaDesc = "%s unidades a cada %s postes",
        kafesTopTitle = "Tela (Total)",
        kafesTopDesc = "Rolo de %s m (%s m de altura)",
        kafesKgTitle = "Peso de 1 rolo de arame",
        kafesKgDesc = "Peso por 1 rolo (%s m).",
        dikenTitle = "Arame farpado",
        dikenDesc = "%d carreiras (%s m/rolo)",
        gergiTitle = "Arame de tensão",
        gergiDesc = "Comprimento / %s",
        baglamaTitle = "Arame de amarração",
        baglamaDesc = "1/%s do arame de tensão",
        cimentoTitle = "Cimento (50 kg)",
        cimentoDesc = "Número de postes / %s",
        betonTitle = "Betão pronto",
        betonDesc = "Número de postes / %s",
        catMetal = "METAL",
        catWire = "ARAME",
        catConstruction = "CONSTRUÇÃO",
        catGeneral = "GERAL"
    )


    private val nl = AppStrings(
        appName = "Hekwerkkalculator",
        readyCalculations = "KLARE BEREKENINGEN",
        settings = "INSTELLINGEN",
        about = "Over",
        personalInfo = "PERSOONLIJKE INFO",
        companyName = "Bedrijfsnaam",
        iban = "IBAN",
        invalidIban = "Ongeldig IBAN-formaat",
        pin = "Vastzetten",
        share = "Delen",
        shareAppTitle = "Delen",
        shareAppMessage = "Professionele oplossing voor uw hekwerk- en gaasbehoeften!\nDownload %s nu:\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "Camera gebruiken",
        selectFromGallery = "Selecteren uit galerij",
        fenceCalculation = "HEKWERKBEREKENING",
        premiumArchitecturalTool = "PREMIUM ARCHITECTURALE TOOL",
        customerNameSurname = "Naam klant",
        preparingPdfReport = "PDF-rapport voorbereiden...",
        customCards = "AANGEPASTE KAARTEN",
        createNewCard = "NIEUWE KAART MAKEN",
        calculationParameters = "Berekeningsparameters",
        calculationParametersDesc = "Wijzigingen worden direct berekend.",
        loadDefaultCards = "Standaardkaarten laden",
        cardTitleRequired = "Kaarttitel *",
        descriptionNote = "Beschrijving / Notitie",
        quantityValue = "Hoeveelheid / Waarde",
        quantity = "Hoeveelheid",
        unitPriceTl = "Eenheidsprijs (€)",
        pdfLoadFailed = "PDF laden mislukt",
        whatsapp = "WhatsApp",
        currencySymbol = "€",
        currencyFormat = "€ %s",
        defaultValueLabel = "Standaard: %s",
        unitLabel = "EENHEID",
        unitPiece = "Stuk",
        unitMeter = "Meter",
        unitKg = "kg",
        unitLiter = "Liter",
        unitUnit = "Eenheid",
        unitTl = "€",
        unitRoll = "Rol",
        unitM3 = "m³",
        searchCountryOrCode = "Zoek land of code...",
        totalLabel = "TOTAAL",
        calculatedAmount = "Berekend bedrag",
        totalCostLabel = "TOTALE KOSTEN",
        customerInfo = "KLANTINFORMATIE",
        favoriteCalculations = "FAVORIETEN",
        sharePdf = "PDF delen",
        infoTextHome = "Gebruik de tabbladen 'Bibliotheek' of 'Aangepast' hieronder om berekeningsdetails te zien.",
        navHome = "Home",
        navCalculations = "Bibliotheek",
        navCustom = "Aangepast",
        navProfile = "Profiel",
        back = "Terug",
        companyInfoTitle = "BEDRIJFSINFORMATIE",
        paymentInfoTitle = "BETALINGSINFORMATIE",
        scanQrCode = "Scan QR-code",
        scanQrCodeTitle = "SCAN QR-CODE",
        cameraPermissionRequired = "Cameratoestemming vereist",
        ibanQrCodeDesc = "IBAN QR-code",
        qrCodeSharingDesc = "QR-code die bij het delen verschijnt",
        noCardsYet = "Nog geen kaarten",
        noCardsDesc = "Personaliseer de app door uw eigen aangepaste berekeningskaarten te maken.",
        editCard = "KAART BEWERKEN",
        addNewCard = "NIEUWE KAART TOEVOEGEN",
        manualEntry = "HANDMATIGE INVOER",
        quantityAndUnit = "HOEVEELHEID & EENHEID",
        selectReferenceCard = "SELECTEER REFERENTIEKAART",
        selectOperation = "SELECTEER BEWERKING",
        opAdd = "Optellen",
        opSub = "Aftrekken",
        opMul = "Vermenigvuldigen",
        opDiv = "Delen",
        calcPreviewResult = "Resultaat: %d %s %s %.1f = %d %s",
        previewTitle = "VOORBEELD",
        totalPreviewText = "Totaal: %s €",
        update = "BIJWERKEN",
        save = "OPSLAAN",
        deleteCard = "KAART VERWIJDEREN",
        appearanceSettings = "Uiterlijk-instellingen",
        themeLight = "Licht",
        themeDark = "Donker",
        themeSystem = "Systeem",
        languageSettings = "Taalinstellingen",
        fencePostDimensions = "Afmetingen hekwerk & palen",
        fenceHeightM = "Hekwerkhoogte (m)",
        poleSpacingM = "Paalafstand (m)",
        wireThicknessMm = "Draaddikte (mm)",
        meshEyeCm = "Maaswijdte (cm)",
        weightConstant = "Gewichtsconstante",
        strutSetup = "Schoreninstallatie",
        strutIntervalPosts = "Interval (palen)",
        strutCountPer = "Hoeveelheid (elk)",
        meshRollSpecs = "Specificaties gaasrol",
        meshRollLengthM = "Rollengte (m)",
        barbedWireRows = "Prikkeldraad (rijen)",
        barbedWireRollM = "Prikkeldraadrol (m)",
        advancedParameters = "Geavanceerde parameters",
        poleLengthM = "Paallengte (m)",
        pipeLengthM = "Buislengte (m)",
        tensionFactor = "Spanningsfactor",
        bindingFactor = "Bindingsfactor",
        cementFactor = "Cementfactor",
        concreteFactor = "Betonfactor",
        aboutAppTitle = "Over de app",
        appDescriptionLong = "%s is een professionele berekeningsassistent voor uw hekwerk- en gaasbehoeften.",
        developerLabel = "Ontwikkelaar",
        feedback = "Feedback",
        feedbackDesc = "Fout melden of functie voorstellen",
        licenses = "Licenties",
        licensesDesc = "Open source bibliotheken",
        allRightsReserved = "© %d %s. Alle rechten voorbehouden.",
        pdfDefaultTitle = "HEKWERKBEREKENING",
        pdfTotalLengthLabel = "Totale weglengte:",
        pdfHeaderMaterial = "MATERIAAL",
        pdfHeaderQty = "HOEVEELHEID",
        pdfHeaderUnitPrice = "EENHEIDSPRIJS",
        pdfHeaderTotal = "TOTAAL BEDRAG",
        pdfGrandTotal = "ALGEHELE TOTALE KOSTEN",
        pdfSharingSubject = "Kostenraming",
        pdfIbanCopiedToast = "IBAN gekopieerd!",
        pdfShareFileSubject = "Hekwerkkostenraming",
        pdfShareFileText = "In de bijlage vindt u het gedetailleerde rapport voor de berekening van de hekwerkkosten.",
        pdfShareChooserTitle = "PDF-rapport delen",
        pdfPreviewTitle = "Voorbeeld raming",
        close = "Sluiten",
        shareAsPdf = "Delen als PDF",
        customerPhoneNo = "Telefoonnummer klant",
        selectCountry = "LAND SELECTEREN",
        unitPriceLabel = "Eenheidsprijs (€)",
        direkTitle = "Paal",
        direkDesc = "Elke %s m",
        boyDemirTitle = "IJzeren buis",
        boyDemirDesc = "%s m (Elke buis levert %s m paal op)",
        payandaTitle = "Schoor",
        payandaDesc = "%s stuks elke %s palen",
        kafesTopTitle = "Gaas (Totaal)",
        kafesTopDesc = "%s m rol (%s m Hoogte)",
        kafesKgTitle = "Gewicht 1 rol gaas",
        kafesKgDesc = "Gewicht per 1 rol (%s m).",
        dikenTitle = "Prikkeldraad",
        dikenDesc = "%d rijen (%s m/rol)",
        gergiTitle = "Spandraad",
        gergiDesc = "Lengte / %s",
        baglamaTitle = "Binddraad",
        baglamaDesc = "1/%s van de spandraad",
        cimentoTitle = "Cement (50 kg)",
        cimentoDesc = "Aantal palen / %s",
        betonTitle = "Betonmortel",
        betonDesc = "Aantal palen / %s",
        catMetal = "METAAL",
        catWire = "DRAAD",
        catConstruction = "BOUW",
        catGeneral = "ALGEMEEN"
    )

    private val fr = AppStrings(
        appName = "Calculateur de Clôture",
        readyCalculations = "CALCULS PRÊTS",
        settings = "PARAMÈTRES",
        about = "À propos",
        personalInfo = "INFOS PERSONNELLES",
        companyName = "Nom de l'entreprise",
        iban = "IBAN",
        invalidIban = "Format IBAN invalide",
        pin = "Épingler",
        share = "Partager",
        shareAppTitle = "Partager",
        shareAppMessage = "Solution professionnelle pour vos besoins de clôtures et de grillages !\nTéléchargez %s maintenant :\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "Utiliser la caméra",
        selectFromGallery = "Sélectionner dans la galerie",
        fenceCalculation = "CALCUL DE CLÔTURE",
        premiumArchitecturalTool = "OUTIL ARCHITECTURAL PREMIUM",
        customerNameSurname = "Nom du client",
        preparingPdfReport = "Préparation du rapport PDF...",
        customCards = "CARTES PERSONNALISÉES",
        createNewCard = "CRÉER UNE NOUVELLE CARTE",
        calculationParameters = "Paramètres de calcul",
        calculationParametersDesc = "Les modifications sont calculées instantanément.",
        loadDefaultCards = "Charger les cartes par défaut",
        cardTitleRequired = "Titre de la carte *",
        descriptionNote = "Description / Note",
        quantityValue = "Quantité / Valeur",
        quantity = "Quantità",
        unitPriceTl = "Prix unitaire (€)",
        pdfLoadFailed = "Échec du chargement du PDF",
        whatsapp = "WhatsApp",
        currencySymbol = "€",
        currencyFormat = "%s €",
        defaultValueLabel = "Par défaut : %s",
        unitLabel = "UNITÉ",
        unitPiece = "Pièce",
        unitMeter = "Mètre",
        unitKg = "kg",
        unitLiter = "Litre",
        unitUnit = "Unité",
        unitTl = "€",
        unitRoll = "Rouleau",
        unitM3 = "m³",
        searchCountryOrCode = "Chercher pays ou code...",
        totalLabel = "TOTAL",
        calculatedAmount = "Montant calculé",
        totalCostLabel = "COÛT TOTAL",
        customerInfo = "INFORMATIONS CLIENT",
        favoriteCalculations = "FAVORIS",
        sharePdf = "Partager PDF",
        infoTextHome = "Utilisez les onglets 'Bilbliothèque' ou 'Personnel' ci-dessous pour voir les détails du calcul.",
        navHome = "Accueil",
        navCalculations = "Bibliothèque",
        navCustom = "Personnel",
        navProfile = "Profil",
        back = "Retour",
        companyInfoTitle = "INFORMATIONS ENTREPRISE",
        paymentInfoTitle = "INFORMATIONS DE PAIEMENT",
        scanQrCode = "Scanner code QR",
        scanQrCodeTitle = "SCANNER CODE QR",
        cameraPermissionRequired = "Permission caméra requise",
        ibanQrCodeDesc = "Code QR IBAN",
        qrCodeSharingDesc = "Code QR qui apparaîtra dans le partage",
        noCardsYet = "Pas encore de cartes",
        noCardsDesc = "Personnalisez l'application en créant vos propres cartes de calcul personnalisées.",
        editCard = "MODIFIER LA CARTE",
        addNewCard = "AJOUTER NOUVELLE CARTE",
        manualEntry = "SAISIE MANUELLE",
        quantityAndUnit = "QUANTITÉ ET UNITÉ",
        selectReferenceCard = "SÉLECTIONNER CARTE DE RÉFÉRENCE",
        selectOperation = "SÉLECTIONNER OPÉRATION",
        opAdd = "Ajouter",
        opSub = "Soustraire",
        opMul = "Multiplier",
        opDiv = "Diviser",
        calcPreviewResult = "Résultat : %d %s %s %.1f = %d %s",
        previewTitle = "APERÇU",
        totalPreviewText = "Total : %s €",
        update = "METTRE À JOUR",
        save = "ENREGISTRER",
        deleteCard = "SUPPRIMER LA CARTE",
        appearanceSettings = "Paramètres d'apparence",
        themeLight = "Clair",
        themeDark = "Sombre",
        themeSystem = "Système",
        languageSettings = "Paramètres de langue",
        fencePostDimensions = "Dimensions clôture et poteaux",
        fenceHeightM = "Hauteur de clôture (m)",
        poleSpacingM = "Espacement des poteaux (m)",
        wireThicknessMm = "Épaisseur du fil (mm)",
        meshEyeCm = "Maille (cm)",
        weightConstant = "Constante de poids",
        strutSetup = "Installation des jambes de force",
        strutIntervalPosts = "Intervalle (poteaux)",
        strutCountPer = "Quantité (chaque fois)",
        meshRollSpecs = "Spécifications rouleau grillage",
        meshRollLengthM = "Longueur du rouleau (m)",
        barbedWireRows = "Fil barbelé (rangées)",
        barbedWireRollM = "Rouleau barbelé (m)",
        advancedParameters = "Paramètres avancés",
        poleLengthM = "Longueur du poteau (m)",
        pipeLengthM = "Longueur du tuyau (m)",
        tensionFactor = "Facteur de tension",
        bindingFactor = "Facteur de ligature",
        cementFactor = "Facteur de ciment",
        concreteFactor = "Facteur de béton",
        aboutAppTitle = "À propos de l'application",
        appDescriptionLong = "%s est un assistant de calcul professionnel pour vos besoins de clôtures et de grillages.",
        developerLabel = "Développeur",
        feedback = "Commentaires",
        feedbackDesc = "Signaler un bug ou suggérer une fonctionnalité",
        licenses = "Licences",
        licensesDesc = "Bibliothèques open source",
        allRightsReserved = "© %d %s. Tous droits réservés.",
        pdfDefaultTitle = "CALCUL DE CLÔTURE",
        pdfTotalLengthLabel = "Longueur totale de la zone :",
        pdfHeaderMaterial = "MATÉRIAU",
        pdfHeaderQty = "QUANTITÉ",
        pdfHeaderUnitPrice = "PRIX UNITAIRE",
        pdfHeaderTotal = "MONTANT TOTAL",
        pdfGrandTotal = "COÛT TOTAL GÉNÉRAL",
        pdfSharingSubject = "Estimation des coûts",
        pdfIbanCopiedToast = "IBAN copié !",
        pdfShareFileSubject = "Estimation du coût de la clôture",
        pdfShareFileText = "Vous trouverez ci-joint le rapport détaillé du calcul du coût de la clôture.",
        pdfShareChooserTitle = "Partager le rapport PDF",
        pdfPreviewTitle = "Aperçu de l'estimation",
        close = "Fermer",
        shareAsPdf = "Partager en PDF",
        customerPhoneNo = "N° de téléphone client",
        selectCountry = "SÉLECTIONNER PAYS",
        unitPriceLabel = "Prix unitaire (€)",
        direkTitle = "Poteau",
        direkDesc = "Tous les %s m",
        boyDemirTitle = "Tuyau en fer",
        boyDemirDesc = "%s m (Chaque tuyau produit un poteau de %s m)",
        payandaTitle = "Jambe de force",
        payandaDesc = "%s unités tous les %s poteaux",
        kafesTopTitle = "Grillage (Total)",
        kafesTopDesc = "Rouleau de %s m (%s m de hauteur)",
        kafesKgTitle = "Poids d'un rouleau de fil",
        kafesKgDesc = "Poids pour 1 rouleau (%s m).",
        dikenTitle = "Fil barbelé",
        dikenDesc = "%d rangées (%s m/rouleau)",
        gergiTitle = "Fil de tension",
        gergiDesc = "Longueur / %s",
        baglamaTitle = "Fil de ligature",
        baglamaDesc = "1/%s du fil de tension",
        cimentoTitle = "Ciment (50 kg)",
        cimentoDesc = "Nombre de poteaux / %s",
        betonTitle = "Béton prêt à l'emploi",
        betonDesc = "Nombre de poteaux / %s",
        catMetal = "MÉTAL",
        catWire = "FIL",
        catConstruction = "CONSTRUCTION",
        catGeneral = "GÉNÉRAL"
    )


    private val es = AppStrings(
        appName = "Calculadora de Cercas",
        readyCalculations = "CÁLCULOS LISTOS",
        settings = "AJUSTES",
        about = "Acerca de",
        personalInfo = "INFORMACIÓN PERSONAL",
        companyName = "Nombre de la empresa",
        iban = "IBAN",
        invalidIban = "Formato IBAN no válido",
        pin = "Fijar",
        share = "Compartir",
        shareAppTitle = "Compartir",
        shareAppMessage = "¡Solución profesional para sus necesidades de cercas y mallas!\nDescargue %s ahora:\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "Usar cámara",
        selectFromGallery = "Seleccionar de la galería",
        fenceCalculation = "CÁLCULO DE CERCAS",
        premiumArchitecturalTool = "HERRAMIENTA ARQUITECTÓNICA PREMIUM",
        customerNameSurname = "Nombre del cliente",
        preparingPdfReport = "Preparando informe PDF...",
        customCards = "TARJETAS PERSONALIZADAS",
        createNewCard = "CREAR NUEVA TARJETA",
        calculationParameters = "Parámetros de cálculo",
        calculationParametersDesc = "Los cambios se calculan instantáneamente.",
        loadDefaultCards = "Cargar tarjetas predeterminadas",
        cardTitleRequired = "Título de la tarjeta *",
        descriptionNote = "Descripción / Nota",
        quantityValue = "Cantidad / Valor",
        quantity = "Cantidad",
        unitPriceTl = "Precio unitario (€)",
        pdfLoadFailed = "Error al cargar el PDF",
        whatsapp = "WhatsApp",
        currencySymbol = "€",
        currencyFormat = "%s €",
        defaultValueLabel = "Predeterminado: %s",
        unitLabel = "UNIDAD",
        unitPiece = "Pieza",
        unitMeter = "Metro",
        unitKg = "kg",
        unitLiter = "Litro",
        unitUnit = "Unidad",
        unitTl = "€",
        unitRoll = "Rollo",
        unitM3 = "m³",
        searchCountryOrCode = "Buscar país o código...",
        totalLabel = "TOTAL",
        calculatedAmount = "Monto calculado",
        totalCostLabel = "COSTO TOTAL",
        customerInfo = "INFORMACIÓN DEL CLIENTE",
        favoriteCalculations = "FAVORITOS",
        sharePdf = "Compartir PDF",
        infoTextHome = "Use las pestañas 'Biblioteca' o 'Personal' a continuación para ver los detalles del cálculo.",
        navHome = "Inicio",
        navCalculations = "Biblioteca",
        navCustom = "Personal",
        navProfile = "Perfil",
        back = "Atrás",
        companyInfoTitle = "INFORMACIÓN DE LA EMPRESA",
        paymentInfoTitle = "INFORMACIÓN DE PAGO",
        scanQrCode = "Escanear código QR",
        scanQrCodeTitle = "ESCANEAR CÓDIGO QR",
        cameraPermissionRequired = "Se requiere permiso de cámara",
        ibanQrCodeDesc = "Código QR IBAN",
        qrCodeSharingDesc = "Código QR que aparecerá al compartir",
        noCardsYet = "Aún no hay tarjetas",
        noCardsDesc = "Personalice la aplicación creando sus propias tarjetas de cálculo personalizadas.",
        editCard = "EDITAR TARJETA",
        addNewCard = "AÑADIR NUEVA TARJETA",
        manualEntry = "ENTRADA MANUAL",
        quantityAndUnit = "CANTIDAD Y UNIDAD",
        selectReferenceCard = "SELECCIONAR TARJETA DE REFERENCIA",
        selectOperation = "SELECCIONAR OPERACIÓN",
        opAdd = "Sumar",
        opSub = "Restar",
        opMul = "Multiplicar",
        opDiv = "Dividir",
        calcPreviewResult = "Resultado: %d %s %s %.1f = %d %s",
        previewTitle = "VISTA PREVIA",
        totalPreviewText = "Total: %s €",
        update = "ACTUALIZAR",
        save = "GUARDAR",
        deleteCard = "ELIMINAR TARJETA",
        appearanceSettings = "Ajustes de apariencia",
        themeLight = "Claro",
        themeDark = "Oscuro",
        themeSystem = "Sistema",
        languageSettings = "Ajustes de idioma",
        fencePostDimensions = "Dimensiones de valla y postes",
        fenceHeightM = "Altura de la valla (m)",
        poleSpacingM = "Espaciado de postes (m)",
        wireThicknessMm = "Grosor del alambre (mm)",
        meshEyeCm = "Malla (cm)",
        weightConstant = "Constante de peso",
        strutSetup = "Instalación de puntales",
        strutIntervalPosts = "Intervalo (postes)",
        strutCountPer = "Cantidad (cada vez)",
        meshRollSpecs = "Especificaciones del rollo de malla",
        meshRollLengthM = "Longitud del rollo (m)",
        barbedWireRows = "Alambre de espino (filas)",
        barbedWireRollM = "Rollo de espino (m)",
        advancedParameters = "Parámetros avanzados",
        poleLengthM = "Longitud del poste (m)",
        pipeLengthM = "Longitud del tubo (m)",
        tensionFactor = "Factor de tensión",
        bindingFactor = "Factor de unión",
        cementFactor = "Factor de cemento",
        concreteFactor = "Factor de hormigón",
        aboutAppTitle = "Acerca de la aplicación",
        appDescriptionLong = "%s es un asistente de cálculo profesional para sus necesidades de cercas y mallas.",
        developerLabel = "Desarrollador",
        feedback = "Comentarios",
        feedbackDesc = "Informar de un error o sugerir una función",
        licenses = "Licencias",
        licensesDesc = "Bibliotecas de código abierto",
        allRightsReserved = "© %d %s. Todos los derechos reservados.",
        pdfDefaultTitle = "CÁLCULO DE CERCAS",
        pdfTotalLengthLabel = "Longitud total del área:",
        pdfHeaderMaterial = "MATERIAL",
        pdfHeaderQty = "CANTIDAD",
        pdfHeaderUnitPrice = "PRECIO UNITARIO",
        pdfHeaderTotal = "MONTO TOTAL",
        pdfGrandTotal = "COSTO TOTAL GENERAL",
        pdfSharingSubject = "Estimación de costos",
        pdfIbanCopiedToast = "¡IBAN copiado!",
        pdfShareFileSubject = "Estimación del costo de la cerca",
        pdfShareFileText = "Se adjunta el informe detallado del cálculo del costo de la cerca.",
        pdfShareChooserTitle = "Compartir informe PDF",
        pdfPreviewTitle = "Vista previa de la estimación",
        close = "Cerrar",
        shareAsPdf = "Compartir como PDF",
        customerPhoneNo = "N.º de teléfono del cliente",
        selectCountry = "SELECCIONAR PAÍS",
        unitPriceLabel = "Precio unitario (€)",
        direkTitle = "Poste",
        direkDesc = "Cada %s m",
        boyDemirTitle = "Tubo de hierro",
        boyDemirDesc = "%s m (Cada tubo produce un poste de %s m)",
        payandaTitle = "Puntal",
        payandaDesc = "%s unidades cada %s postes",
        kafesTopTitle = "Malla (Total)",
        kafesTopDesc = "Rollo de %s m (%s m de altura)",
        kafesKgTitle = "Peso de 1 rollo de alambre",
        kafesKgDesc = "Peso por 1 rollo (%s m).",
        dikenTitle = "Alambre de espino",
        dikenDesc = "%d filas (%s m/rollo)",
        gergiTitle = "Alambre de tensión",
        gergiDesc = "Longitud / %s",
        baglamaTitle = "Alambre de unión",
        baglamaDesc = "1/%s del alambre de tensión",
        cimentoTitle = "Cemento (50 kg)",
        cimentoDesc = "Número de postes / %s",
        betonTitle = "Hormigón premezclado",
        betonDesc = "Número de postes / %s",
        catMetal = "METAL",
        catWire = "ALAMBRE",
        catConstruction = "CONSTRUCCIÓN",
        catGeneral = "GENERAL"
    )


    private val en = AppStrings(
        appName = "Fence Calculator",
        readyCalculations = "READY CALCULATIONS",
        settings = "SETTINGS",
        about = "About",
        personalInfo = "PERSONAL INFORMATION",
        companyName = "Company Name",
        iban = "IBAN",
        invalidIban = "Invalid IBAN format",
        pin = "Pin",
        share = "Share",
        shareAppTitle = "Share",
        shareAppMessage = "Professional solution for your fence and mesh wire needs!\nDownload %s now:\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "Use Camera",
        selectFromGallery = "Select from Gallery",
        fenceCalculation = "FENCE CALCULATION",
        premiumArchitecturalTool = "PREMIUM ARCHITECTURAL TOOL",
        customerNameSurname = "Customer Name",
        preparingPdfReport = "Preparing PDF Report...",
        customCards = "CUSTOM CARDS",
        createNewCard = "CREATE NEW CARD",
        calculationParameters = "Calculation Parameters",
        calculationParametersDesc = "Changes are calculated instantly.",
        loadDefaultCards = "Load Default Cards",
        cardTitleRequired = "Card Title *",
        descriptionNote = "Description / Note",
        quantityValue = "Quantity / Value",
        quantity = "Quantity",
        unitPriceTl = "Unit Price (₺)",
        pdfLoadFailed = "PDF Failed to Load",
        whatsapp = "WhatsApp",
        currencySymbol = "$",
        currencyFormat = "$ %s",
        defaultValueLabel = "Default: %s",
        unitLabel = "UNIT",
        unitPiece = "Piece",
        unitMeter = "Meter",
        unitKg = "Kg",
        unitLiter = "Liter",
        unitUnit = "Unit",
        unitTl = "TL",
        unitRoll = "Roll",
        unitM3 = "m³",
        searchCountryOrCode = "Search country or code...",
        totalLabel = "TOTAL",
        calculatedAmount = "Calculated Amount",
        totalCostLabel = "TOTAL COST",
        customerInfo = "CUSTOMER INFORMATION",
        favoriteCalculations = "FAVORITE CALCULATIONS",
        sharePdf = "Share PDF",
        infoTextHome = "Use 'Library' or 'Custom' tabs below to see calculation details.",
        navHome = "Home",
        navCalculations = "Library",
        navCustom = "Custom",
        navProfile = "Profile",
        back = "Back",
        companyInfoTitle = "COMPANY INFORMATION",
        paymentInfoTitle = "PAYMENT INFORMATION",
        scanQrCode = "Scan QR Code",
        scanQrCodeTitle = "SCAN QR CODE",
        cameraPermissionRequired = "Camera permission required",
        ibanQrCodeDesc = "IBAN QR Code",
        qrCodeSharingDesc = "QR code that will appear on sharing",
        noCardsYet = "No Cards Yet",
        noCardsDesc = "Personalize the app by creating your own custom calculation cards.",
        editCard = "EDIT CARD",
        addNewCard = "ADD NEW CARD",
        manualEntry = "MANUAL ENTRY",
        quantityAndUnit = "QUANTITY & UNIT",
        selectReferenceCard = "SELECT REFERENCE CARD",
        selectOperation = "SELECT OPERATION",
        opAdd = "Add",
        opSub = "Subtract",
        opMul = "Multiply",
        opDiv = "Divide",
        calcPreviewResult = "Result: %d %s %s %.1f = %d %s",
        previewTitle = "PREVIEW",
        totalPreviewText = "Total: %s ₺",
        update = "UPDATE",
        save = "SAVE",
        deleteCard = "DELETE CARD",
        appearanceSettings = "Appearance Settings",
        themeLight = "Light",
        themeDark = "Dark",
        themeSystem = "System",
        languageSettings = "Language Settings",
        fencePostDimensions = "Fence & Post Dimensions",
        fenceHeightM = "Fence Height (m)",
        poleSpacingM = "Pole Spacing (m)",
        wireThicknessMm = "Wire Thickness (mm)",
        meshEyeCm = "Mesh Eye (cm)",
        weightConstant = "Weight Constant",
        strutSetup = "Strut Setup",
        strutIntervalPosts = "Interval (Posts)",
        strutCountPer = "Quantity (Each)",
        meshRollSpecs = "Mesh Roll Specs",
        meshRollLengthM = "Mesh Roll Length (m)",
        barbedWireRows = "Barbed Wire (Rows)",
        barbedWireRollM = "Barbed Roll (m)",
        advancedParameters = "Advanced Parameters",
        poleLengthM = "Pole Length (m)",
        pipeLengthM = "Pipe Length (m)",
        tensionFactor = "Tension Factor",
        bindingFactor = "Binding Factor",
        cementFactor = "Cement Factor",
        concreteFactor = "Concrete Factor",
        aboutAppTitle = "About Application",
        appDescriptionLong = "%s is a professional calculation assistant for your fence and mesh wire needs.",
        developerLabel = "Developer",
        feedback = "Feedback",
        feedbackDesc = "Report a bug or suggest a feature",
        licenses = "Licenses",
        licensesDesc = "Open source libraries",
        allRightsReserved = "© %d %s. All rights reserved.",
        pdfDefaultTitle = "FENCE CALCULATION",
        pdfTotalLengthLabel = "Total Area Length:",
        pdfHeaderMaterial = "MATERIAL",
        pdfHeaderQty = "QUANTITY",
        pdfHeaderUnitPrice = "UNIT PRICE",
        pdfHeaderTotal = "TOTAL",
        pdfGrandTotal = "GRAND TOTAL COST",
        pdfSharingSubject = "Cost Estimate",
        pdfIbanCopiedToast = "IBAN copied!",
        pdfShareFileSubject = "Fence Cost Estimate",
        pdfShareFileText = "Please find the detailed fence cost calculation report attached.",
        pdfShareChooserTitle = "Share PDF Report",
        pdfPreviewTitle = "Estimate Preview",
        close = "Close",
        shareAsPdf = "Share as PDF",
        customerPhoneNo = "Customer Phone No",
        selectCountry = "SELECT COUNTRY",
        unitPriceLabel = "Unit Price (₺)",
        direkTitle = "Post",
        direkDesc = "Every %s m",
        boyDemirTitle = "Iron Pipe",
        boyDemirDesc = "%s m (Each pipe yields %s m post)",
        payandaTitle = "Strut",
        payandaDesc = "%s units every %s posts",
        kafesTopTitle = "Mesh Wire (Total)",
        kafesTopDesc = "%s m roll (%s m Height)",
        kafesKgTitle = "1 Roll Wire Weight",
        kafesKgDesc = "Weight for 1 roll (%s m).",
        dikenTitle = "Barbed Wire",
        dikenDesc = "%d Rows (%s m/roll)",
        gergiTitle = "Tension Wire",
        gergiDesc = "Length / %s",
        baglamaTitle = "Binding Wire",
        baglamaDesc = "1/%s of Tension Wire",
        cimentoTitle = "Cement (50 Kg)",
        cimentoDesc = "Post Count / %s",
        betonTitle = "Ready-Mixed Concrete",
        betonDesc = "Post Count / %s",
        catMetal = "METAL",
        catWire = "WIRE",
        catConstruction = "CONSTRUCTION",
        catGeneral = "GENERAL"
    )
    private val ru = AppStrings(
        appName = "Калькулятор Ограждений",
        readyCalculations = "ГОТОВЫЕ РАСЧЕТЫ",
        settings = "НАСТРОЙКИ",
        about = "О приложении",
        personalInfo = "ЛИЧНАЯ ИНФОРМАЦИЯ",
        companyName = "Название компании",
        iban = "IBAN",
        invalidIban = "Неверный формат IBAN",
        pin = "Закрепить",
        share = "Поделиться",
        shareAppTitle = "Поделиться",
        shareAppMessage = "Профессиональное решение для ваших нужд в ограждениях и сетке!\nСкачайте %s прямо сейчас:\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "Использовать камеру",
        selectFromGallery = "Выбрать из галереи",
        fenceCalculation = "РАСЧЕТ ОГРАЖДЕНИЯ",
        premiumArchitecturalTool = "ПРЕМИАЛЬНЫЙ АРХИТЕКТУРНЫЙ ИНСТРУМЕНТ",
        customerNameSurname = "Имя клиента",
        preparingPdfReport = "Подготовка PDF-отчета...",
        customCards = "ПОЛЬЗОВАТЕЛЬСКИЕ КАРТЫ",
        createNewCard = "СОЗДАТЬ НОВУЮ КАРТУ",
        calculationParameters = "Параметры расчета",
        calculationParametersDesc = "Изменения рассчитываются мгновенно.",
        loadDefaultCards = "Загрузить стандартные карты",
        cardTitleRequired = "Заголовок карты *",
        descriptionNote = "Описание / Примечание",
        quantityValue = "Количество / Значение",
        quantity = "Количество",
        unitPriceTl = "Цена за единицу (₺)",
        pdfLoadFailed = "Ошибка загрузки PDF",
        whatsapp = "WhatsApp",
        currencySymbol = "₽",
        currencyFormat = "%s ₽",
        defaultValueLabel = "По умолчанию: %s",
        unitLabel = "ЕДИНИЦА",
        unitPiece = "Шт.",
        unitMeter = "Метр",
        unitKg = "Кг",
        unitLiter = "Литр",
        unitUnit = "Ед.",
        unitTl = "₺",
        unitRoll = "Рулон",
        unitM3 = "м³",
        searchCountryOrCode = "Поиск страны или кода...",
        totalLabel = "ИТОГО",
        calculatedAmount = "Рассчитанная сумма",
        totalCostLabel = "ОБЩАЯ СТОИМОСТЬ",
        customerInfo = "ИНФОРМАЦИЯ О КЛИЕНТЕ",
        favoriteCalculations = "ИЗБРАННОЕ",
        sharePdf = "Поделиться PDF",
        infoTextHome = "Используйте вкладки 'Библиотека' или 'Свои' ниже, чтобы увидеть детали расчета.",
        navHome = "Главная",
        navCalculations = "Библиотека",
        navCustom = "Свои",
        navProfile = "Профиль",
        back = "Назад",
        companyInfoTitle = "ИНФОРМАЦИЯ О КОМПАНИИ",
        paymentInfoTitle = "ИНФОРМАЦИЯ ОБ ОПЛАТЕ",
        scanQrCode = "Сканировать QR-код",
        scanQrCodeTitle = "СКАНИРОВАТЬ QR-КОД",
        cameraPermissionRequired = "Требуется разрешение на использование камеры",
        ibanQrCodeDesc = "QR-код IBAN",
        qrCodeSharingDesc = "QR-код, который появится при публикации",
        noCardsYet = "Карт пока нет",
        noCardsDesc = "Персонализируйте приложение, создавая свои собственные карты расчетов.",
        editCard = "РЕДАКТИРОВАТЬ КАРТУ",
        addNewCard = "ДОБАВИТЬ НОВУЮ КАРТУ",
        manualEntry = "РУЧНОЙ ВВОД",
        quantityAndUnit = "КОЛ-ВО И ЕДИНИЦА",
        selectReferenceCard = "ВЫБЕРИТЕ СПРАВОЧНУЮ КАРТУ",
        selectOperation = "ВЫБЕРИТЕ ОПЕРАЦИЮ",
        opAdd = "Сложить",
        opSub = "Вычесть",
        opMul = "Умножить",
        opDiv = "Разделить",
        calcPreviewResult = "Результат: %d %s %s %.1f = %d %s",
        previewTitle = "ПРЕДПРОСМОТР",
        totalPreviewText = "Итого: %s ₺",
        update = "ОБНОВИТЬ",
        save = "СОХРАНИТЬ",
        deleteCard = "УДАЛИТЬ КАРТУ",
        appearanceSettings = "Настройки внешнего вида",
        themeLight = "Светлая",
        themeDark = "Темная",
        themeSystem = "Системная",
        languageSettings = "Языковые настройки",
        fencePostDimensions = "Размеры забора и столбов",
        fenceHeightM = "Высота забора (м)",
        poleSpacingM = "Расстояние между столбами (м)",
        wireThicknessMm = "Толщина проволоки (мм)",
        meshEyeCm = "Ячейка сетки (см)",
        weightConstant = "Коэффициент веса",
        strutSetup = "Установка подкосов",
        strutIntervalPosts = "Интервал (столбы)",
        strutCountPer = "Количество (каждый раз)",
        meshRollSpecs = "Характеристики рулона сетки",
        meshRollLengthM = "Длина рулона (м)",
        barbedWireRows = "Колючая проволока (ряды)",
        barbedWireRollM = "Рулон колючей проволоки (м)",
        advancedParameters = "Расширенные параметры",
        poleLengthM = "Длина столба (м)",
        pipeLengthM = "Длина трубы (м)",
        tensionFactor = "Коэффициент натяжения",
        bindingFactor = "Коэффициент вязки",
        cementFactor = "Коэффициент цемента",
        concreteFactor = "Коэффициент бетона",
        aboutAppTitle = "О приложении",
        appDescriptionLong = "%s — это профессиональный помощник для расчета ваших нужд в ограждениях и сетке.",
        developerLabel = "Разработчик",
        feedback = "Обратная связь",
        feedbackDesc = "Сообщить об ошибке или предложить функцию",
        licenses = "Licences",
        licensesDesc = "Библиотеки с открытым исходным кодом",
        allRightsReserved = "© %d %s. Все права защищены.",
        pdfDefaultTitle = "РАСЧЕТ ЗАБОРА",
        pdfTotalLengthLabel = "Общая длина участка:",
        pdfHeaderMaterial = "МАТЕРИАЛ",
        pdfHeaderQty = "КОЛИЧЕСТВО",
        pdfHeaderUnitPrice = "ЦЕНА ЗА ЕД.",
        pdfHeaderTotal = "ИТОГОВАЯ СУММА",
        pdfGrandTotal = "ОБЩАЯ СТОИМОСТЬ",
        pdfSharingSubject = "Смета затрат",
        pdfIbanCopiedToast = "IBAN скопирован!",
        pdfShareFileSubject = "Смета затрат на забор",
        pdfShareFileText = "Во вложении вы найдете подробный отчет о расчете стоимости забора.",
        pdfShareChooserTitle = "Поделиться PDF-отчетом",
        pdfPreviewTitle = "Предпросмотр сметы",
        close = "Закрыть",
        shareAsPdf = "Поделиться в формате PDF",
        customerPhoneNo = "Телефон клиента",
        selectCountry = "ВЫБЕРИТЕ СТРАНУ",
        unitPriceLabel = "Цена за единицу (₺)",
        direkTitle = "Столб",
        direkDesc = "Каждые %s м",
        boyDemirTitle = "Железная труба",
        boyDemirDesc = "%s м (Из каждой трубы получается столб %s м)",
        payandaTitle = "Подкос",
        payandaDesc = "%s шт. на каждые %s столбов",
        kafesTopTitle = "Сетка (Всего)",
        kafesTopDesc = "Рулон %s м (высота %s м)",
        kafesKgTitle = "Вес 1 рулона проволоки",
        kafesKgDesc = "Вес 1 рулона (%s м).",
        dikenTitle = "Колючая проволока",
        dikenDesc = "%d ряда(ов) (%s м/рулон)",
        gergiTitle = "Натяжная проволока",
        gergiDesc = "Длина / %s",
        baglamaTitle = "Вязальная проволока",
        baglamaDesc = "1/%s от натяжной проволоки",
        cimentoTitle = "Цемент (50 кг)",
        cimentoDesc = "Кол-во столбов / %s",
        betonTitle = "Товарный бетон",
        betonDesc = "Кол-во столбов / %s",
        catMetal = "МЕТАЛЛ",
        catWire = "ПРОВОЛОКА",
        catConstruction = "СТРОИТЕЛЬСТВО",
        catGeneral = "ОБЩЕЕ"
    )


    private val ar = AppStrings(
        appName = "حاسبة السياج",
        readyCalculations = "حسابات جاهزة",
        settings = "الإعدادات",
        about = "حول التطبيق",
        personalInfo = "معلومات شخصية",
        companyName = "اسم الشركة",
        iban = "IBAN",
        invalidIban = "صيغة IBAN غير صالحة",
        pin = "تثبيت",
        share = "مشاركة",
        shareAppTitle = "مشاركة",
        shareAppMessage = "حل احترافي لاحتياجاتك من السياج والأسلاك الشبكية!\nحمل %s الآن:\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "استخدام الكاميرا",
        selectFromGallery = "اختر من المعرض",
        fenceCalculation = "حساب السياج",
        premiumArchitecturalTool = "أداة معمارية متميزة",
        customerNameSurname = "اسم العميل",
        preparingPdfReport = "جاري إعداد تقرير PDF...",
        customCards = "بطاقات مخصصة",
        createNewCard = "إنشاء بطاقة جديدة",
        calculationParameters = "معايير الحساب",
        calculationParametersDesc = "يتم احتساب التغييرات فوراً.",
        loadDefaultCards = "تحميل البطاقات الافتراضية",
        cardTitleRequired = "عنوان البطاقة *",
        descriptionNote = "الوصف / ملاحظة",
        quantityValue = "الكمية / القيمة",
        quantity = "الكمية",
        unitPriceTl = "سعر الوحدة (₺)",
        pdfLoadFailed = "فشل تحميل PDF",
        whatsapp = "واتساب",
        currencySymbol = "﷼",
        currencyFormat = "%s ﷼",
        defaultValueLabel = "الافتراضي: %s",
        unitLabel = "الوحدة",
        unitPiece = "قطعة",
        unitMeter = "متر",
        unitKg = "كجم",
        unitLiter = "لتر",
        unitUnit = "وحدة",
        unitTl = "₺",
        unitRoll = "لفة",
        unitM3 = "م³",
        searchCountryOrCode = "ابحث عن دولة أو رمز...",
        totalLabel = "الإجمالي",
        calculatedAmount = "المبلغ المحسوب",
        totalCostLabel = "التكلفة الإجمالية",
        customerInfo = "معلومات العميل",
        favoriteCalculations = "الحسابات المفضلة",
        sharePdf = "مشاركة PDF",
        infoTextHome = "استخدم علامتي التبويب 'المكتبة' أو 'مخصص' أدناه لمشاهدة تفاصيل الحساب.",
        navHome = "الرئيسية",
        navCalculations = "المكتبة",
        navCustom = "مخصص",
        navProfile = "الملف الشخصي",
        back = "رجوع",
        companyInfoTitle = "معلومات الشركة",
        paymentInfoTitle = "معلومات الدفع",
        scanQrCode = "مسح رمز QR",
        scanQrCodeTitle = "مسح رمز QR",
        cameraPermissionRequired = "مطلوب إذن الكاميرا",
        ibanQrCodeDesc = "رمز QR لـ IBAN",
        qrCodeSharingDesc = "رمز QR الذي سيظهر عند المشاركة",
        noCardsYet = "لا يوجد بطاقات بعد",
        noCardsDesc = "قم بتخصيص التطبيق عن طريق إنشاء بطاقات حساب مخصصة خاصة بك.",
        editCard = "تعديل البطاقة",
        addNewCard = "إضافة بطاقة جديدة",
        manualEntry = "إدخال يدوي",
        quantityAndUnit = "الكمية والوحدة",
        selectReferenceCard = "اختر بطاقة مرجعية",
        selectOperation = "اختر عملية",
        opAdd = "جمع",
        opSub = "طرح",
        opMul = "ضرب",
        opDiv = "قسمة",
        calcPreviewResult = "النتيجة: %d %s %s %.1f = %d %s",
        previewTitle = "معاينة",
        totalPreviewText = "الإجمالي: %s ₺",
        update = "تحديث",
        save = "حفظ",
        deleteCard = "حذف البطاقة",
        appearanceSettings = "إعدادات المظهر",
        themeLight = "فاتح",
        themeDark = "داكن",
        themeSystem = "النظام",
        languageSettings = "إعدادات اللغة",
        fencePostDimensions = "أبعاد السياج والأعمدة",
        fenceHeightM = "ارتفاع السياج (م)",
        poleSpacingM = "المسافة بين الأعمدة (م)",
        wireThicknessMm = "سمك السلك (مم)",
        meshEyeCm = "فتحة الشبكة (سم)",
        weightConstant = "ثابت الوزن",
        strutSetup = "تركيب الدعامات",
        strutIntervalPosts = "المدة (أعمدة)",
        strutCountPer = "الكمية (في كل مرة)",
        meshRollSpecs = "مواصفات لفة الشبكة",
        meshRollLengthM = "طول اللفة (م)",
        barbedWireRows = "سلك شائك (صفوف)",
        barbedWireRollM = "لفة شائكة (م)",
        advancedParameters = "معلمات متقدمة",
        poleLengthM = "طول العمود (م)",
        pipeLengthM = "طول الأنبوب (م)",
        tensionFactor = "معامل الشد",
        bindingFactor = "معامل الربط",
        cementFactor = "معامل الأسمنت",
        concreteFactor = "معامل الخرسانة",
        aboutAppTitle = "حول التطبيق",
        appDescriptionLong = "%s هو مساعد حساب احترافي لاحتياجاتك من السياج والأسلاك الشبكية.",
        developerLabel = "المطور",
        feedback = "التعليقات",
        feedbackDesc = "بلغ عن خطأ أو اقترح ميزة",
        licenses = "Licences",
        licensesDesc = "المكتبات مفتوحة المصدر",
        allRightsReserved = "© %d %s. جميع الحقوق محفوظة.",
        pdfDefaultTitle = "حساب السياج",
        pdfTotalLengthLabel = "إجمالي طول الأرض:",
        pdfHeaderMaterial = "المادة",
        pdfHeaderQty = "الكمية",
        pdfHeaderUnitPrice = "سعر الوحدة",
        pdfHeaderTotal = "إجمالي المبلغ",
        pdfGrandTotal = "إجمالي التكلفة العامة",
        pdfSharingSubject = "تقدير التكلفة",
        pdfIbanCopiedToast = "تم نسخ IBAN!",
        pdfShareFileSubject = "تقدير تكلفة السياج",
        pdfShareFileText = "تجدون مرفقاً تقرير تفصيلي لحساب تكلفة السياج.",
        pdfShareChooserTitle = "مشاركة تقرير PDF",
        pdfPreviewTitle = "معاينة التقدير",
        close = "إغلاق",
        shareAsPdf = "مشاركة كـ PDF",
        customerPhoneNo = "رقم هاتف العميل",
        selectCountry = "اختر الدولة",
        unitPriceLabel = "سعر الوحدة (₺)",
        direkTitle = "عمود",
        direkDesc = "كل %s م",
        boyDemirTitle = "أنبوب حديدي",
        boyDemirDesc = "%s م (كل أنبوب يعطي عموداً بطول %s م)",
        payandaTitle = "دعامة",
        payandaDesc = "%s وحدات لكل %s أعمدة",
        kafesTopTitle = "شبكة (إجمالي)",
        kafesTopDesc = "لفة %s م (ارتفاع %s م)",
        kafesKgTitle = "وزن لفة سلك واحدة",
        kafesKgDesc = "الوزن لكل لفة واحدة (%s م).",
        dikenTitle = "سلك شائك",
        dikenDesc = "%d صفوف (%s م/لفة)",
        gergiTitle = "سلك شد",
        gergiDesc = "الطول / %s",
        baglamaTitle = "سلك ربط",
        baglamaDesc = "1/%s من سلك الشد",
        cimentoTitle = "أسمنت (50 كجم)",
        cimentoDesc = "عدد الأعمدة / %s",
        betonTitle = "خرسانة جاهزة",
        betonDesc = "عدد الأعمدة / %s",
        catMetal = "معدن",
        catWire = "سلك",
        catConstruction = "إنشاءات",
        catGeneral = "عام"
    )

    private val de = AppStrings(
        appName = "Zaunrechner",
        readyCalculations = "FERTIGE BERECHNUNGEN",
        settings = "EINSTELLUNGEN",
        about = "Über",
        personalInfo = "PERSÖNLICHE INFO",
        companyName = "Firmenname",
        iban = "IBAN",
        invalidIban = "Ungültiges IBAN-Format",
        pin = "Anheften",
        share = "Teilen",
        shareAppTitle = "Teilen",
        shareAppMessage = "Professionelle Lösung für Ihren Zaun- und Maschendrahtbedarf!\nLaden Sie %s jetzt herunter:\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "Kamera benutzen",
        selectFromGallery = "Aus Galerie wählen",
        fenceCalculation = "ZAUNBERECHNUNG",
        premiumArchitecturalTool = "PREMIUM ARCHITEKTUR-TOOL",
        customerNameSurname = "Kundenname",
        preparingPdfReport = "PDF-Bericht wird vorbereitet...",
        customCards = "BENUTZERDEFINIERTE KARTEN",
        createNewCard = "NEUE KARTE ERSTELLEN",
        calculationParameters = "Berechnungsparameter",
        calculationParametersDesc = "Änderungen werden sofort berechnet.",
        loadDefaultCards = "Standardkarten laden",
        cardTitleRequired = "Kartentitel *",
        descriptionNote = "Beschreibung / Notiz",
        quantityValue = "Menge / Wert",
        quantity = "Menge",
        unitPriceTl = "Einzelpreis (€)",
        pdfLoadFailed = "PDF-Laden fehlgeschlagen",
        whatsapp = "WhatsApp",
        currencySymbol = "€",
        currencyFormat = "%s €",
        defaultValueLabel = "Standard: %s",
        unitLabel = "EINHEIT",
        unitPiece = "Stück",
        unitMeter = "Meter",
        unitKg = "kg",
        unitLiter = "Liter",
        unitUnit = "Einheit",
        unitTl = "€",
        unitRoll = "Rolle",
        unitM3 = "m³",
        searchCountryOrCode = "Land oder Code suchen...",
        totalLabel = "GESAMT",
        calculatedAmount = "Berechneter Betrag",
        totalCostLabel = "GESAMTKOSTEN",
        customerInfo = "KUNDENINFORMATION",
        favoriteCalculations = "FAVORITEN",
        sharePdf = "PDF teilen",
        infoTextHome = "Verwenden Sie die Tabs 'Bibliothek' oder 'Eigene' unten, um Berechnungsdetails zu sehen.",
        navHome = "Home",
        navCalculations = "Bibliothek",
        navCustom = "Eigene",
        navProfile = "Profil",
        back = "Zurück",
        companyInfoTitle = "FIRMENINFORMATION",
        paymentInfoTitle = "ZAHLUNGSINFORMATION",
        scanQrCode = "QR-Code scannen",
        scanQrCodeTitle = "QR-CODE SCANNEN",
        cameraPermissionRequired = "Kameraberechtigung erforderlich",
        ibanQrCodeDesc = "IBAN QR-Code",
        qrCodeSharingDesc = "QR-Code, der beim Teilen erscheint",
        noCardsYet = "Noch keine Karten",
        noCardsDesc = "Personalisieren Sie die App, indem Sie Ihre eigenen benutzerdefinierten Berechnungskarten erstellen.",
        editCard = "KARTE BEARBEITEN",
        addNewCard = "NEUE KARTE HINZUFÜGEN",
        manualEntry = "MANUELLE EINGABE",
        quantityAndUnit = "MENGE & EINHEIT",
        selectReferenceCard = "REFERENZKARTE WÄHLEN",
        selectOperation = "OPERATION WÄHLEN",
        opAdd = "Addieren",
        opSub = "Subtrahieren",
        opMul = "Multiplizieren",
        opDiv = "Dividieren",
        calcPreviewResult = "Ergebnis: %d %s %s %.1f = %d %s",
        previewTitle = "VORSCHAU",
        totalPreviewText = "Gesamt: %s €",
        update = "AKTUALISIEREN",
        save = "SPEICHERN",
        deleteCard = "KARTE LÖSCHEN",
        appearanceSettings = "Erscheinungsbild-Einstellungen",
        themeLight = "Hell",
        themeDark = "Dunkel",
        themeSystem = "System",
        languageSettings = "Spracheinstellungen",
        fencePostDimensions = "Zaun- & Pfostenmaße",
        fenceHeightM = "Zaunhöhe (m)",
        poleSpacingM = "Pfostenabstand (m)",
        wireThicknessMm = "Drahtstärke (mm)",
        meshEyeCm = "Maschenweite (cm)",
        weightConstant = "Gewichtskonstante",
        strutSetup = "Strebenmontage",
        strutIntervalPosts = "Intervall (Pfosten)",
        strutCountPer = "Menge (pro Mal)",
        meshRollSpecs = "Spezifikationen Maschenrolle",
        meshRollLengthM = "Rollenlänge (m)",
        barbedWireRows = "Stacheldraht (Reihen)",
        barbedWireRollM = "Stacheldrahtrolle (m)",
        advancedParameters = "Erweiterte Parameter",
        poleLengthM = "Pfostenlänge (m)",
        pipeLengthM = "Rohrlänge (m)",
        tensionFactor = "Spannfaktor",
        bindingFactor = "Bindefaktor",
        cementFactor = "Zementfaktor",
        concreteFactor = "Betonfaktor",
        aboutAppTitle = "Über die App",
        appDescriptionLong = "%s ist ein professioneller Berechnungsassistent für Ihren Zaun- und Maschendrahtbedarf.",
        developerLabel = "Entwickler",
        feedback = "Feedback",
        feedbackDesc = "Fehler melden oder Funktion vorschlagen",
        licenses = "Lizenzen",
        licensesDesc = "Open-Source-Bibliotheken",
        allRightsReserved = "© %d %s. Alle Rechte vorbehalten.",
        pdfDefaultTitle = "ZAUNBERECHNUNG",
        pdfTotalLengthLabel = "Gesamtlänge des Bereichs:",
        pdfHeaderMaterial = "MATERIAL",
        pdfHeaderQty = "MENGE",
        pdfHeaderUnitPrice = "EINZELPREIS",
        pdfHeaderTotal = "GESAMTBETRAG",
        pdfGrandTotal = "GESAMTKOSTEN",
        pdfSharingSubject = "Kostenvoranschlag",
        pdfIbanCopiedToast = "IBAN kopiert!",
        pdfShareFileSubject = "Zaunkostenvoranschlag",
        pdfShareFileText = "Anbei finden Sie den detaillierten Bericht zur Zaunkostenberechnung.",
        pdfShareChooserTitle = "PDF-Bericht teilen",
        pdfPreviewTitle = "Vorschau Kostenvoranschlag",
        close = "Schließen",
        shareAsPdf = "Als PDF teilen",
        customerPhoneNo = "Kundentelefonnummer",
        selectCountry = "LAND WÄHLEN",
        unitPriceLabel = "Einzelpreis (€)",
        direkTitle = "Pfosten",
        direkDesc = "Alle %s m",
        boyDemirTitle = "Eisenrohr",
        boyDemirDesc = "%s m (Jedes Rohr ergibt einen Pfosten von %s m)",
        payandaTitle = "Strebe",
        payandaDesc = "%s Einheiten alle %s Pfosten",
        kafesTopTitle = "Maschendraht (Gesamt)",
        kafesTopDesc = "%s m Rolle (%s m Höhe)",
        kafesKgTitle = "Gewicht 1 Drahtrolle",
        kafesKgDesc = "Gewicht für 1 Rolle (%s m).",
        dikenTitle = "Stacheldraht",
        dikenDesc = "%d Reihen (%s m/Rolle)",
        gergiTitle = "Spanndraht",
        gergiDesc = "Länge / %s",
        baglamaTitle = "Bindedraht",
        baglamaDesc = "1/%s des Spanndrahts",
        cimentoTitle = "Zement (50 kg)",
        cimentoDesc = "Pfostenanzahl / %s",
        betonTitle = "Transportbeton",
        betonDesc = "Pfostenanzahl / %s",
        catMetal = "METALL",
        catWire = "DRAHT",
        catConstruction = "KONSTRUKTION",
        catGeneral = "ALLGEMEIN"
    )

    private val zh = AppStrings(
        appName = "围栏计算器",
        readyCalculations = "准备计算",
        settings = "设置",
        about = "关于",
        personalInfo = "个人信息",
        companyName = "公司名称",
        iban = "IBAN",
        invalidIban = "IBAN格式无效",
        pin = "置顶",
        share = "分享",
        shareAppTitle = "分享",
        shareAppMessage = "专业的围栏和网线需求解决方案！\n立即下载 %s：\nhttps://play.google.com/store/apps/details?id=com.vahitkeskin.fencecalculator",
        useCamera = "使用摄像头",
        selectFromGallery = "从相册选择",
        fenceCalculation = "围栏计算",
        premiumArchitecturalTool = "高级建筑工具",
        customerNameSurname = "客户姓名",
        preparingPdfReport = "正在准备 PDF 报告...",
        customCards = "自定义卡片",
        createNewCard = "创建新卡片",
        calculationParameters = "计算参数",
        calculationParametersDesc = "更改将立即计算。",
        loadDefaultCards = "加载默认卡片",
        cardTitleRequired = "卡片标题 *",
        descriptionNote = "描述 / 备注",
        quantityValue = "数量 / 数值",
        quantity = "数量",
        unitPriceTl = "单价 (₺)",
        pdfLoadFailed = "PDF 加载失败",
        whatsapp = "WhatsApp",
        currencySymbol = "¥",
        currencyFormat = "¥ %s",
        defaultValueLabel = "默认: %s",
        unitLabel = "单位",
        unitPiece = "件",
        unitMeter = "米",
        unitKg = "公斤",
        unitLiter = "升",
        unitUnit = "单位",
        unitTl = "₺",
        unitRoll = "卷",
        unitM3 = "立方米",
        searchCountryOrCode = "搜索国家或代码...",
        totalLabel = "总计",
        calculatedAmount = "计算金额",
        totalCostLabel = "总成本",
        customerInfo = "客户信息",
        favoriteCalculations = "我的收藏",
        sharePdf = "分享 PDF",
        infoTextHome = "使用下面的“库”或“自定义”选项卡查看计算详情。",
        navHome = "首页",
        navCalculations = "库",
        navCustom = "自定义",
        navProfile = "个人资料",
        back = "返回",
        companyInfoTitle = "公司信息",
        paymentInfoTitle = "付款信息",
        scanQrCode = "扫描二维码",
        scanQrCodeTitle = "扫描二维码",
        cameraPermissionRequired = "需要摄像头权限",
        ibanQrCodeDesc = "IBAN 二维码",
        qrCodeSharingDesc = "分享时显示的二维码",
        noCardsYet = "暂无卡片",
        noCardsDesc = "通过创建您自己的自定义计算卡片来个性化应用。",
        editCard = "编辑卡片",
        addNewCard = "添加新卡片",
        manualEntry = "手动输入",
        quantityAndUnit = "数量和单位",
        selectReferenceCard = "选择参考卡片",
        selectOperation = "选择操作",
        opAdd = "加",
        opSub = "减",
        opMul = "乘",
        opDiv = "除",
        calcPreviewResult = "结果: %d %s %s %.1f = %d %s",
        previewTitle = "预览",
        totalPreviewText = "总计: %s ₺",
        update = "更新",
        save = "保存",
        deleteCard = "删除卡片",
        appearanceSettings = "外观设置",
        themeLight = "浅色",
        themeDark = "深色",
        themeSystem = "系统",
        languageSettings = "语言设置",
        fencePostDimensions = "围栏和支柱尺寸",
        fenceHeightM = "围栏高度 (m)",
        poleSpacingM = "支柱间距 (m)",
        wireThicknessMm = "钢丝厚度 (mm)",
        meshEyeCm = "网孔 (cm)",
        weightConstant = "重量常数",
        strutSetup = "支撑安装",
        strutIntervalPosts = "间隔 (支柱)",
        strutCountPer = "数量 (每次)",
        meshRollSpecs = "网卷规格",
        meshRollLengthM = "卷长 (m)",
        barbedWireRows = "刺绳 (行)",
        barbedWireRollM = "刺绳卷 (m)",
        advancedParameters = "高级参数",
        poleLengthM = "支柱长度 (m)",
        pipeLengthM = "管长 (m)",
        tensionFactor = "张力系数",
        bindingFactor = "绑扎系数",
        cementFactor = "水泥系数",
        concreteFactor = "混凝土系数",
        aboutAppTitle = "关于应用",
        appDescriptionLong = "%s 是围栏和网线需求的专业计算助手。",
        developerLabel = "开发者",
        feedback = "反馈",
        feedbackDesc = "报告错误或提出建议",
        licenses = "Licences",
        licensesDesc = "开源库",
        allRightsReserved = "© %d %s. 保留所有权利。",
        pdfDefaultTitle = "围栏计算",
        pdfTotalLengthLabel = "总占地面积长度:",
        pdfHeaderMaterial = "材料",
        pdfHeaderQty = "数量",
        pdfHeaderUnitPrice = "单价",
        pdfHeaderTotal = "总金额",
        pdfGrandTotal = "总成本",
        pdfSharingSubject = "成本估算",
        pdfIbanCopiedToast = "IBAN 已复制！",
        pdfShareFileSubject = "围栏成本估算",
        pdfShareFileText = "请查收附件中的围栏成本计算详细报告。",
        pdfShareChooserTitle = "分享 PDF 报告",
        pdfPreviewTitle = "估算预览",
        close = "关闭",
        shareAsPdf = "分享为 PDF",
        customerPhoneNo = "客户电话",
        selectCountry = "选择国家",
        unitPriceLabel = "单价 (₺)",
        direkTitle = "支柱",
        direkDesc = "每 %s 米",
        boyDemirTitle = "铁管",
        boyDemirDesc = "%s 米 (每根管产出 %s 米支柱)",
        payandaTitle = "支撑",
        payandaDesc = "每 %s 根支柱 %s 个",
        kafesTopTitle = "网线 (总计)",
        kafesTopDesc = "%s 米卷 (%s 米高度)",
        kafesKgTitle = "一卷钢丝重量",
        kafesKgDesc = "一卷 (%s 米) 的重量。",
        dikenTitle = "刺绳",
        dikenDesc = "%d 行 (%s 米/卷)",
        gergiTitle = "张紧线",
        gergiDesc = "长度 / %s",
        baglamaTitle = "绑扎线",
        baglamaDesc = "张紧线的 1/%s",
        cimentoTitle = "水泥 (50 公斤)",
        cimentoDesc = "支柱数量 / %s",
        betonTitle = "商品混凝土",
        betonDesc = "支柱数量 / %s",
        catMetal = "金属",
        catWire = "丝",
        catConstruction = "建筑",
        catGeneral = "通用"
    )

    private val languages = mapOf(
        "tr" to tr,
        "en" to en,
        "de" to de,
        "fr" to fr,
        "es" to es,
        "it" to it,
        "pt" to pt,
        "nl" to nl,
        "ru" to ru,
        "ar" to ar,
        "zh" to zh
    )

    fun getStrings(locale: String): AppStrings {
        return languages[locale] ?: en
    }

    // Keep legacy getString for backward compatibility during transition
    fun getString(key: String, language: AppLanguage, vararg args: Any): String {
        val strings = getStrings(language.code)
        // Since we refactored to data class, we should ideally access properties directly.
        // For the transition, we'll map common keys or return the key if not found.
        // This is a temporary measure until all call sites are refactored.
        val value = when(key) {
            "app_name" -> strings.appName
            "ready_calculations" -> strings.readyCalculations
            "settings" -> strings.settings
            "about" -> strings.about
            "personal_info" -> strings.personalInfo
            "company_name" -> strings.companyName
            "iban" -> strings.iban
            "invalid_iban" -> strings.invalidIban
            "pin" -> strings.pin
            "share" -> strings.share
            "share_app_title" -> strings.shareAppTitle
            "share_app_message" -> strings.shareAppMessage
            "use_camera" -> strings.useCamera
            "select_from_gallery" -> strings.selectFromGallery
            "fence_calculation" -> strings.fenceCalculation
            "premium_architectural_tool" -> strings.premiumArchitecturalTool
            "customer_name_surname" -> strings.customerNameSurname
            "preparing_pdf_report" -> strings.preparingPdfReport
            "custom_cards" -> strings.customCards
            "create_new_card" -> strings.createNewCard
            "calculation_parameters" -> strings.calculationParameters
            "calculation_parameters_desc" -> strings.calculationParametersDesc
            "load_default_cards" -> strings.loadDefaultCards
            "card_title_required" -> strings.cardTitleRequired
            "description_note" -> strings.descriptionNote
            "quantity_value" -> strings.quantityValue
            "quantity" -> strings.quantity
            "unit_price_tl" -> strings.unitPriceTl
            "pdf_load_failed" -> strings.pdfLoadFailed
            "whatsapp" -> strings.whatsapp
            "total_label" -> strings.totalLabel
            "calculated_amount" -> strings.calculatedAmount
            "total_cost_label" -> strings.totalCostLabel
            "customer_info" -> strings.customerInfo
            "favorite_calculations" -> strings.favoriteCalculations
            "share_pdf" -> strings.sharePdf
            "nav_home" -> strings.navHome
            "nav_calculations" -> strings.navCalculations
            "nav_custom" -> strings.navCustom
            "nav_profile" -> strings.navProfile
            "back" -> strings.back
            "save" -> strings.save
            "update" -> strings.update
            "delete_card" -> strings.deleteCard
            "appearance_settings" -> strings.appearanceSettings
            "language_settings" -> strings.languageSettings
            "direk_title" -> strings.direkTitle
            "direk_desc" -> strings.direkDesc
            "boy_demir_title" -> strings.boyDemirTitle
            "boy_demir_desc" -> strings.boyDemirDesc
            "payanda_title" -> strings.payandaTitle
            "payanda_desc" -> strings.payandaDesc
            "kafes_top_title" -> strings.kafesTopTitle
            "kafes_top_desc" -> strings.kafesTopDesc
            "kafes_kg_title" -> strings.kafesKgTitle
            "kafes_kg_desc" -> strings.kafesKgDesc
            "diken_title" -> strings.dikenTitle
            "diken_desc" -> strings.dikenDesc
            "gergi_title" -> strings.gergiTitle
            "gergi_desc" -> strings.gergiDesc
            "baglama_title" -> strings.baglamaTitle
            "baglama_desc" -> strings.baglamaDesc
            "cimento_title" -> strings.cimentoTitle
            "cimento_desc" -> strings.cimentoDesc
            "beton_title" -> strings.betonTitle
            "beton_desc" -> strings.betonDesc
            "unit_piece" -> strings.unitPiece
            "unit_meter" -> strings.unitMeter
            "unit_kg" -> strings.unitKg
            "unit_liter" -> strings.unitLiter
            "unit_unit" -> strings.unitUnit
            "unit_roll" -> strings.unitRoll
            "unit_m3" -> strings.unitM3
            "cat_metal" -> strings.catMetal
            "cat_wire" -> strings.catWire
            "cat_construction" -> strings.catConstruction
            "cat_general" -> strings.catGeneral
            else -> key
        }
        
        return try {
            if (args.isEmpty()) value else String.format(value, *args)
        } catch (e: Exception) {
            value
        }
    }
}
